-- Auto-generated complete language entries for hashibasha_language schema
-- Total keys: 845
-- Sources: i18n.ts fallback, comprehensive-translations.sql, code extraction

CREATE SCHEMA IF NOT EXISTS hashibasha_language;

CREATE TABLE IF NOT EXISTS hashibasha_language.language_entries (
  id SERIAL PRIMARY KEY,
  key VARCHAR(255) UNIQUE NOT NULL,
  en TEXT NOT NULL,
  ar TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO hashibasha_language.language_entries (key, en, ar) VALUES
('absent', 'Absent', 'غائب'),
('action', 'Action', 'إجراء'),
('actionPoint', 'Action Point', 'نقطة العمل'),
('actionPointDetails', 'Action Point Details', 'تفاصيل نقطة العمل'),
('actionPoints', 'Action Points', 'نقاط العمل'),
('actionPointsIntro', 'Action Points Intro', 'Action Points Intro'),
('actionPointsReports', 'Action Points Reports', 'تقارير نقاط العمل'),
('actionPointsReportsDesc', 'Track issue resolution, overdue items, and assignee performance.', 'تتبع حل المشكلات والعناصر المتأخرة وأداء المكلفين.'),
('actionPointTab', 'Action Point', 'نقطة العمل'),
('actionPointTitlePlaceholder', 'Action Point Title Placeholder', 'Action Point Title Placeholder'),
('actions', 'Actions', 'الإجراءات'),
('active', 'Active', 'نشط'),
('activeStatus', 'Active Status', 'Active Status'),
('activity', 'Activity', 'Activity'),
('activityOverview', 'Activity Overview', 'نظرة عامة على النشاط'),
('add', 'Add', 'إضافة'),
('addAdvanceMapping', 'Add Advance Mapping', 'إضافة تعيين متقدم'),
('addANewTagToTheSystem', 'Add a new tag to the system', 'إضافة علامة جديدة إلى النظام'),
('addAuditTitleBeforeAssigning', 'Add Audit Title Before Assigning', 'Add Audit Title Before Assigning'),
('addComment', 'Add Comment', 'إضافة تعليق'),
('addDesignation', 'Add Designation', 'إضافة مسمى وظيفي'),
('addNewEntity', 'Add New Entity', 'إضافة كيان جديد'),
('addNewUser', 'Add New User', 'إضافة مستخدم جديد'),
('address', 'Address', 'العنوان'),
('addValue', 'Add Value', 'إضافة قيمة'),
('admins', 'Admins', 'Admins'),
('advanceMapping', 'Advance Mapping', 'التعيين المتقدم'),
('advanceMappingAddDescription', 'Select a user and choose additional stores for report access.', 'اختر مستخدماً وحدد المتاجر الإضافية لصلاحية التقارير.'),
('advanceMappingAdditionalStores', 'Additional stores', 'المتاجر الإضافية'),
('advanceMappingAddTitle', 'Add Advance Mapping', 'إضافة تعيين متقدم'),
('advanceMappingCreate', 'Create', 'إنشاء'),
('advanceMappingCreated', 'Advance mapping created', 'تم إنشاء التعيين المتقدم'),
('advanceMappingDefaultStore', 'default store', 'المتجر الافتراضي'),
('advanceMappingDefaultStoreHint', 'Default store cannot be added as an additional mapping.', 'لا يمكن إضافة المتجر الافتراضي كتعيين إضافي.'),
('advanceMappingDeleteConfirm', 'Remove all advance mapping for this user?', 'إزالة كل التعيين المتقدم لهذا المستخدم؟'),
('advanceMappingDeleted', 'Advance mapping removed', 'تمت إزالة التعيين المتقدم'),
('advanceMappingDeleteFailed', 'Failed to remove advance mapping', 'فشلت إزالة التعيين المتقدم'),
('advanceMappingDescription', 'Give users report access to additional stores beyond their default mapped stores.', 'منح المستخدمين صلاحية الوصول إلى تقارير متاجر إضافية بخلاف المتجر الافتراضي المعين لهم.'),
('advanceMappingEditDescription', 'Update additional stores this user can access for reporting:', 'حدّث المتاجر الإضافية التي يمكن لهذا المستخدم الوصول إليها للتقارير:'),
('advanceMappingEditTitle', 'Edit Report Access', 'تعديل صلاحية التقارير'),
('advanceMappingEmpty', 'No advance mapped users yet. Click "Add Advance Mapping" to assign report access.', 'لا يوجد مستخدمون معينون بعد. انقر "إضافة تعيين متقدم" لتعيين صلاحية التقارير.'),
('advanceMappingNoEligibleStores', 'This user already has access only to their default store. Add more stores in Organization Management to create advance mappings.', 'لدى هذا المستخدم صلاحية متجره الافتراضي فقط. أضف المزيد من المتاجر في إدارة المنظمة لإنشاء تعيينات متقدمة.'),
('advanceMappingNone', 'None', 'لا يوجد'),
('advanceMappingNoStoresAvailable', 'No stores available', 'لا توجد متاجر متاحة'),
('advanceMappingNoStoresHint', 'Create additional stores in Organization Management before assigning advance report access.', 'أنشئ متاجر إضافية في إدارة المنظمة قبل تعيين صلاحيات التقارير المتقدمة.'),
('advanceMappingSaveFailed', 'Failed to save advance mapping', 'فشل حفظ التعيين المتقدم'),
('advanceMappingSelectStore', 'Select at least one additional store for report access', 'اختر متجراً إضافياً واحداً على الأقل لصلاحية التقارير'),
('advanceMappingSelectUser', 'Select a user first', 'اختر مستخدماً أولاً'),
('advanceMappingSelectUserFirst', 'Select a user first to enable store selection.', 'اختر مستخدماً أولاً لتمكين اختيار المتاجر.'),
('advanceMappingStores', 'Stores for Report Access', 'المتاجر لصلاحية التقارير'),
('advanceMappingTitle', 'Advance Mapping - Report Access', 'التعيين المتقدم - صلاحية التقارير'),
('advanceMappingUpdate', 'Update Mapping', 'تحديث التعيين'),
('advanceMappingUpdated', 'Advance mapping updated', 'تم تحديث التعيين المتقدم'),
('advanceSearch', 'Advance Search', 'بحث متقدم'),
('advDropdownTag', 'Adv Dropdown Tag', 'علامة القائمة المنسدلة المتقدمة'),
('alerts', 'Alerts', 'التنبيهات'),
('alertsAndActivity', 'Alerts and Activity', 'التنبيهات والنشاط'),
('all', 'All', 'الكل'),
('allPeriods', 'All Periods', 'جميع الفترات'),
('allPriority', 'All Priority', 'جميع الأولويات'),
('allStatus', 'All Status', 'كل الحالات'),
('allTime', 'All Time', 'All Time'),
('apply', 'Apply', 'تطبيق'),
('applyFilters', 'Apply Filters', 'تطبيق الفلاتر'),
('approvalsTab', 'Approvals', 'الموافقات'),
('arabicLanguage', 'Arabic Language', 'العربية'),
('arabicName', 'Arabic Name', 'الاسم بالعربية'),
('archived', 'Archived', 'أرشيف'),
('area', 'Area', 'المنطقة'),
('areYouSureDeletePost', 'Are you sure you want to delete this post?', 'هل أنت متأكد من أنك تريد حذف هذا المنشور؟'),
('areYouSureYouWantToDeleteThisProfile', 'Are you sure you want to delete this profile?', 'هل أنت متأكد أنك تريد حذف هذا الملف التعريفي؟'),
('areYouSureYouWantToDeleteThisTag', 'Are you sure you want to delete this tag?', 'هل أنت متأكد أنك تريد حذف هذه العلامة؟'),
('assessmentReport', 'Assessment Report', 'تقرير التقييم'),
('assessmentReports', 'Assessment Reports', 'تقارير التقييمات'),
('assessments', 'Assessments', 'التقييمات'),
('assessmentsList', 'Assessments List', 'قائمة التقييمات'),
('assessmentsQuizzes', 'Assessments & Quizzes', 'التقييمات والاختبارات'),
('assetReports', 'Asset Reports', 'تقارير الأصول'),
('assetReportsDesc', 'Track asset status, expiry, renewal, utilization, and history.', 'تتبع حالة الأصول والانتهاء والتجديد والاستخدام والسجل.'),
('assetsManagement', 'Assets Management', 'إدارة الأصول'),
('assign', 'Assign', 'تعيين'),
('assignAuditTags', 'Assign Audit Tags', 'Assign Audit Tags'),
('assignBeforePublishing', 'Assign Before Publishing', 'Assign Before Publishing'),
('assignBy', 'Assign By', 'تعيين بواسطة'),
('assigned', 'Assigned', 'مسند'),
('assignedAudit', 'Assigned Audit', 'Assigned Audit'),
('assignedChecklist', 'Assigned Checklist', 'Assigned Checklist'),
('assignedStores', 'Assigned Stores', 'المتاجر المعينة'),
('assignedTo', 'Assigned to', 'مسند إلى'),
('assignedToMe', 'Assigned to me', 'مسند إلي'),
('assigneeProfile', 'Assignee Profile', 'ملف المكلف'),
('assignees', 'Assignees', 'المسندون'),
('assignmentSaved', 'Assignment Saved', 'Assignment Saved'),
('attendanceTracking', 'Attendance Tracking', 'تتبع الحضور'),
('audit', 'Audit', 'Audit'),
('auditAssignTab', 'Audit Assign Tab', 'Audit Assign Tab'),
('auditBuildTab', 'Audit Build Tab', 'Audit Build Tab'),
('auditDescriptionPlaceholder', 'Audit Description Placeholder', 'Audit Description Placeholder'),
('auditLabel', 'Audit Label', 'Audit Label'),
('auditPropertiesTab', 'Audit Properties Tab', 'Audit Properties Tab'),
('auditPublished', 'Audit Published', 'Audit Published'),
('audits', 'Audits', 'عمليات التدقيق'),
('auditSavedAsDraft', 'Audit Saved As Draft', 'Audit Saved As Draft'),
('auditSubmittedSuccessfully', 'Audit Submitted Successfully', 'Audit Submitted Successfully'),
('auditTab', 'Audit', 'التدقيق'),
('auditTitle', 'Audit Title', 'Audit Title'),
('auditTitlePlaceholder', 'Audit Title Placeholder', 'Audit Title Placeholder'),
('auditTitleRequired', 'Audit Title Required', 'Audit Title Required'),
('auditTitleTab', 'Audit Title Tab', 'Audit Title Tab'),
('available', 'Available', 'Available'),
('availableQuizzes', 'Available Quizzes', 'الاختبارات المتاحة'),
('back', 'Back', 'رجوع'),
('backToTasks', 'Back To Tasks', 'العودة إلى المهام'),
('bulkEntity', 'Bulk Entity', 'الكيان الجماعي'),
('bulkUploadEntities', 'Bulk Upload Entities', 'تحميل الكيانات الجماعي'),
('bulkUploadEntitiesDescription', 'Upload a CSV or Excel file to create multiple entities at once', 'تحميل ملف CSV أو Excel لإنشاء كيانات متعددة دفعة واحدة'),
('bulkUploadFailed', 'Bulk Upload Failed', 'Bulk Upload Failed'),
('bulkUploadSuccessful', 'Bulk Upload Successful', 'Bulk Upload Successful'),
('bulkUploadUsers', 'Bulk Upload Users', 'رفع المستخدمين جماعياً'),
('bulkUploadUsersDescription', 'Upload a CSV or Excel file to create multiple users at once', 'قم برفع ملف CSV أو Excel لإنشاء مستخدمين متعددين دفعة واحدة'),
('bulkUser', 'Bulk User', 'مستخدم جماعي'),
('businessInfoTab', 'Business Info Tab', 'معلومات العمل'),
('cancel', 'Cancel', 'إلغاء'),
('cancelChanges', 'Cancel changes', 'إلغاء التغييرات'),
('canCreateWorkflows', 'Can create workflows', 'يمكن إنشاء مهام سير العمل'),
('cannotCreateWorkflows', 'Cannot create workflows', 'لا يمكن إنشاء مهام سير العمل'),
('categories', 'Categories', 'Categories'),
('categoriesAndCourses', 'Categories and Courses', 'الفئات والدورات'),
('category1', 'Category1', 'Category1'),
('category2', 'Category2', 'Category2'),
('category3', 'Category3', 'Category3'),
('categoryCreatedSuccessfully', 'Category created successfully', 'تم إنشاء الفئة بنجاح'),
('categoryDeletedSuccessfully', 'Category deleted successfully', 'تم حذف الفئة بنجاح'),
('categoryName', 'Category Name', 'اسم الفئة'),
('categoryNameIsRequired', 'Category Name Is Required', 'Category Name Is Required'),
('categoryUpdatedSuccessfully', 'Category updated successfully', 'تم تحديث الفئة بنجاح'),
('ccsidRetrievedPreview', 'Ccsid Retrieved Preview', 'Ccsid Retrieved Preview'),
('certificateIssued', 'Certificate issuance', 'إصدار الشهادة'),
('changePassword', 'Change Password', 'تغيير كلمة المرور'),
('changePasswordDescription', 'Update your password to keep your account secure', 'قم بتحديث كلمة المرور للحفاظ على أمان حسابك'),
('changeViewLayout', 'Change view layout', 'تغيير طريقة العرض'),
('checkedIn', 'Checked In', 'مسجّل الدخول'),
('checkingSystemStatus', 'Checking system status...', 'جاري التحقق من حالة النظام...'),
('chooseStoreLocation', 'Choose Store Location', 'Choose Store Location'),
('city', 'City', 'المدينة'),
('clickToUploadCsvOrExcelFile', 'Click to upload CSV or Excel file', 'انقر لتحميل ملف CSV أو Excel'),
('close', 'Close', 'إغلاق'),
('closed', 'Closed', 'مغلق'),
('closureAssigned', 'Closure Assigned', 'مسند للإغلاق'),
('collapse', 'Collapse', 'طي'),
('collapseAll', 'Collapse All', 'طي الكل'),
('comments', 'Comments', 'التعليقات'),
('completed', 'Completed', 'مكتمل'),
('completionRate', 'Completion Rate', 'معدل الإكمال'),
('configureSettings', 'Configure {{title}} settings', 'تكوين إعدادات {{title}}'),
('configureSystemPreferences', 'Configure system preferences', 'تكوين تفضيلات النظام'),
('confirmDeleteAudit', 'Confirm Delete Audit', 'Confirm Delete Audit'),
('confirmDeleteDraftProcess', 'Confirm Delete Draft Process', 'Confirm Delete Draft Process'),
('confirmDeleteEntity', 'Confirm Delete Entity', 'Confirm Delete Entity'),
('confirmDeletePublishedProcess', 'Confirm Delete Published Process', 'Confirm Delete Published Process'),
('confirmDiscardDraftAndStartFresh', 'Confirm Discard Draft And Start Fresh', 'Confirm Discard Draft And Start Fresh'),
('confirmNewPassword', 'Confirm New Password', 'تأكيد كلمة المرور الجديدة'),
('contactSupport', 'Contact Support', 'اتصل بالدعم'),
('continue', 'Continue', 'Continue'),
('continueToBuild', 'Continue To Build', 'Continue To Build'),
('continueWorkingOnDrafts', 'Continue working on your drafts', 'متابعة العمل على مسوداتك'),
('correction', 'Correction', 'تصحيح'),
('couldNotLoadUsersOrStores', 'Could Not Load Users Or Stores', 'Could Not Load Users Or Stores'),
('couldNotStartAudit', 'Could Not Start Audit', 'Could Not Start Audit'),
('couldNotSyncAuditDraft', 'Could Not Sync Audit Draft', 'Could Not Sync Audit Draft'),
('courseCompletionReminders', 'Course completion reminders', 'تذكيرات إكمال الدورة'),
('courseCompletionRemindersHint', 'Remind you to finish assigned courses before the due date or when overdue.', 'تذكيرك بإنهاء الدورات المعينة قبل موعد الاستحقاق أو عند التأخير.'),
('courseCreatedSuccessfully', 'Course created successfully', 'تم إنشاء الدورة بنجاح'),
('courseDeletedSuccessfully', 'Course deleted successfully', 'تم حذف الدورة بنجاح'),
('courseNameIsRequired', 'Course Name Is Required', 'Course Name Is Required'),
('courses', 'Courses', 'الدورات'),
('courseUpdatedSuccessfully', 'Course updated successfully', 'تم تحديث الدورة بنجاح'),
('create', 'Create', 'إنشاء'),
('createAdvancedDropdownTag', 'Create Advanced Dropdown Tag', 'إنشاء علامة قائمة منسدلة متقدمة'),
('createAndManage', 'Create and manage assessments', 'إنشاء وإدارة التقييمات'),
('createAsset', 'Create Asset', 'Create Asset'),
('createAssigneeProfile', 'Create Assignee Profile', 'إنشاء ملف تعيين المكلف'),
('createCategory', 'Create Category', 'إنشاء فئة'),
('createCourse', 'Create Course', 'إنشاء دورة'),
('createCourseQuiz', 'Create Course Quiz', 'إنشاء اختبار الدورة'),
('createdAt', 'Created At', 'تم الإنشاء في'),
('createdBy', 'Created by', 'أنشأه'),
('createdByMe', 'Created by me', 'أنشأته أنا'),
('createDesignation', 'Create Designation', 'إنشاء مسمى وظيفي'),
('createDropdownTagWithMultipleValues', 'Create a dropdown tag with multiple values for use in processes and tasks.', 'إنشاء علامة قائمة منسدلة بقيم متعددة للاستخدام في العمليات والمهام.'),
('createEntity', 'Create Entity', 'إنشاء كيان'),
('createFirstProcess', 'Create your first process to get started', 'أنشئ أول عملية للبدء'),
('createFromTemplate', 'Create from Template', 'إنشاء من قالب'),
('createNewAnnouncementOrUpdate', 'Create a new announcement or update for your team.', 'إنشاء إعلان أو تحديث جديد لفريقك.'),
('createNewAssessment', 'Create New Assessment', 'إنشاء تقييم جديد'),
('createNewCategoryToGetStarted', 'Create a new category to get started', 'أنشئ فئة جديدة للبدء'),
('createNewProcess', 'Create New Process', 'إنشاء عملية جديدة'),
('createNewProfile', 'Create New Profile', 'إنشاء ملف تعريف جديد'),
('createNewQuizToGetStarted', 'Create a new quiz to get started', 'أنشئ اختبارًا جديدًا للبدء'),
('createNewTeam', 'Create New Team', 'إنشاء فريق جديد'),
('createNoticeboardPost', 'Create Noticeboard Post', 'إنشاء منشور لوحة الإعلانات'),
('createPost', 'Create Post', 'إنشاء منشور'),
('createProfileWithAssignedStores', 'Create a profile with assigned stores for task assignments.', 'إنشاء ملف تعريف مع المتاجر المعينة لمهام العمل.'),
('createStoreAuditsDescription', 'Create Store Audits Description', 'Create Store Audits Description'),
('createTag', 'Create Tag', 'إنشاء علامة'),
('createTagWithValue', 'Create Tag With Value', 'إنشاء علامة بقيمة'),
('createTeam', 'Create Team', 'إنشاء الفريق'),
('createUser', 'Create User', 'إنشاء مستخدم'),
('createUserTeam', 'Create User Team', 'إنشاء فريق مستخدمين'),
('creationAndConfigurations', 'Creation and Configurations', 'الإنشاء والتكوينات'),
('creationDate', 'Creation Date', 'Creation Date'),
('creatorAccess', 'Creator Access', 'وصول المنشئ'),
('creatorMode', 'Creator Mode', 'وضع المبدع'),
('critical', 'Critical', 'Critical'),
('csrConfigTab', 'Csr Config Tab', 'تكوين شهادة CSR'),
('csrGeneratedPreview', 'Csr Generated Preview', 'Csr Generated Preview'),
('currentEmailFrequency', 'Current', 'الحالي'),
('currentPassword', 'Current Password', 'كلمة المرور الحالية'),
('currentPasswordIncorrect', 'Current password is incorrect', 'كلمة المرور الحالية غير صحيحة'),
('customDashboards', 'Custom Dashboards', 'لوحات المعلومات المخصصة'),
('customDashboardsDesc', 'Build tailored Process, Ticket & Action Point dashboards with bar, line, pie, and table charts, filters, sharing, and templates.', 'أنشئ لوحات مخصصة للعمليات والتذاكر ونقاط العمل مع مخططات شريطية وخطية ودائرية وجداول وفلاتر ومشاركة وقوالب.'),
('customizeTableColumns', 'Customize Table Columns', 'تخصيص أعمدة الجدول'),
('customReports', 'Custom Reports', 'التقارير المخصصة'),
('customReportsContentComingSoon', 'Custom Reports Content Coming Soon', 'محتوى التقارير المخصصة قادم قريباً'),
('dailyDigest', 'Daily Digest', 'الملخص اليومي'),
('dashboardTemplateLibrary', 'Dashboard Template Library', 'مكتبة قوالب لوحات المعلومات'),
('dashboardTemplateLibraryDesc', 'Start quickly with pre-built dashboard layouts for process, ticket, and action point reporting.', 'ابدأ بسرعة باستخدام تخطيطات جاهزة لتقارير العمليات والتذاكر ونقاط العمل.'),
('date', 'Date', 'التاريخ'),
('dateRange', 'Date Range', 'Date Range'),
('days', 'days', 'أيام'),
('deadlineAlerts', 'Deadline Alerts', 'تنبيهات المواعيد النهائية'),
('delete', 'Delete', 'حذف'),
('deleted', 'Deleted', 'محذوف'),
('description', 'Description', 'الوصف'),
('designation', 'Designation', 'المسمى الوظيفي'),
('desktopAlerts', 'Desktop alerts', 'تنبيهات سطح المكتب'),
('discardDraft', 'Discard Draft', 'Discard Draft'),
('discussionsDisabled', 'Discussions Disabled', 'المناقشات معطلة'),
('discussionsEnabled', 'Discussions Enabled', 'المناقشات مفعلة'),
('district', 'District', 'الحي'),
('draft', 'Draft', 'مسودة'),
('draftDiscarded', 'Draft Discarded', 'Draft Discarded'),
('draftProcesses', 'Draft Processes', 'عمليات مسودة'),
('draftSaved', 'Draft Saved', 'Draft Saved'),
('draftSavedContinueFromTasks', 'Draft Saved Continue From Tasks', 'Draft Saved Continue From Tasks'),
('draftTab', 'Draft', 'مسودة'),
('dropdownValues', 'Dropdown Values', 'قيم القائمة المنسدلة'),
('dueDate', 'Due Date', 'تاريخ الاستحقاق'),
('dueToday', 'Due Today', 'مستحق اليوم'),
('edit', 'Edit', 'تعديل'),
('editAssigneeProfile', 'Edit Assignee Profile', 'تعديل ملف تعيين المكلف'),
('editEntity', 'Edit Entity', 'تعديل الكيان'),
('editNoticeboardPost', 'Edit Noticeboard Post', 'تعديل منشور لوحة الإعلانات'),
('editTag', 'Edit Tag', 'تعديل العلامة'),
('editUser', 'Edit User', 'تعديل المستخدم'),
('editUserTeam', 'Edit User Team', 'تعديل فريق المستخدمين'),
('email', 'Email', 'البريد الإلكتروني'),
('emailAsc', 'Email (ASC)', 'البريد الإلكتروني (تصاعدي)'),
('emailConfig', 'Email Config', 'إعداد البريد الإلكتروني'),
('emailConfigSaved', 'Email configuration saved', 'تم حفظ إعداد البريد الإلكتروني'),
('emailDeliveryAddress', 'Delivery address', 'عنوان التسليم'),
('emailDesc', 'Email (DESC)', 'البريد الإلكتروني (تنازلي)'),
('emailFrequency', 'Email frequency', 'تكرار البريد الإلكتروني'),
('emailFrequencyHint', 'Daily and weekly digests batch non-urgent emails. Urgent-only sends high-priority alerts immediately.', 'تجمّع الملخصات اليومية والأسبوعية رسائل البريد غير العاجلة. وضع العاجل فقط يرسل التنبيهات عالية الأولوية فوراً.'),
('emailNotifications', 'Email Notifications', 'إشعارات البريد الإلكتروني'),
('emailNotificationsDisabled', 'Email notifications are turned off.', 'إشعارات البريد الإلكتروني متوقفة.'),
('emailNotificationTypes', 'Email notification types', 'أنواع إشعارات البريد'),
('emailNotificationTypesHint', 'Choose which updates are sent to your email. In-app settings are configured separately.', 'اختر التحديثات التي تُرسل إلى بريدك. إعدادات داخل التطبيق منفصلة أدناه.'),
('employeeId', 'Employee ID', 'معرف الموظف'),
('enabled', 'Enabled', 'مفعّل'),
('enableDiscussions', 'Enable Discussions', 'Enable Discussions'),
('enableEmailNotifications', 'Enable email notifications', 'تفعيل إشعارات البريد الإلكتروني'),
('english', 'English', 'الإنجليزية'),
('enterArabicName', 'Enter Arabic name', 'أدخل الاسم بالعربية'),
('enterArea', 'Enter area', 'أدخل المنطقة'),
('enterAssessmentDescription', 'Enter assessment description', 'أدخل وصف التقييم'),
('enterAssessmentTitle', 'Enter assessment title', 'أدخل عنوان التقييم'),
('enterCategoryName', 'Enter category name', 'أدخل اسم الفئة'),
('enterCity', 'Enter city', 'أدخل المدينة'),
('enterCurrentPassword', 'Enter current password', 'أدخل كلمة المرور الحالية'),
('enterEmail', 'Enter email', 'أدخل البريد الإلكتروني'),
('enterEmployeeId', 'Enter employee ID', 'أدخل معرف الموظف'),
('enterEntityId', 'Enter entity ID', 'أدخل معرف الكيان'),
('enterMediaUrl', 'Enter media URL', 'أدخل رابط الوسائط'),
('enterName', 'Enter name', 'أدخل الاسم'),
('enterNewPassword', 'Enter new password', 'أدخل كلمة المرور الجديدة'),
('enterPhoneNumber', 'Enter phone number', 'أدخل رقم الهاتف'),
('enterPostDescription', 'Enter post description', 'أدخل وصف المنشور'),
('enterPostTitle', 'Enter post title', 'أدخل عنوان المنشور'),
('enterStaffCount', 'Enter staff count', 'أدخل عدد الموظفين'),
('enterStoreName', 'Enter store name', 'أدخل اسم المتجر'),
('enterTag', 'Enter Tag', 'Enter Tag'),
('enterTagName', 'Enter tag name', 'أدخل اسم العلامة'),
('enterTagValueAndPressEnterOrClickAdd', 'Enter tag value and press Enter or click Add', 'أدخل قيمة العلامة واضغط Enter أو انقر على إضافة'),
('enterYourComment', 'Enter your comment...', 'أدخل تعليقك...'),
('enterYourEmail', 'Enter your email', 'أدخل بريدك الإلكتروني'),
('enterYourPassword', 'Enter your password', 'أدخل كلمة المرور'),
('entitiesManagement', 'Entities Management', 'إدارة الكيانات'),
('entity', 'Entity', 'الكيان'),
('entityCreatedSuccessfully', 'Entity created successfully', 'تم إنشاء الكيان بنجاح'),
('entityCreateFailed', 'Failed to create entity', 'فشل إنشاء الكيان'),
('entityId', 'Entity ID', 'معرف الكيان'),
('entityInfoTab', 'Entity Info Tab', 'Entity Info Tab'),
('entityUpdateFailed', 'Failed to update entity', 'فشل تحديث الكيان'),
('exampleButton', 'Example Button', 'زر مثال'),
('examplePage', 'Example Page', 'صفحة مثال'),
('executives', 'Executives', 'Executives'),
('expand', 'Expand', 'توسيع'),
('expandAll', 'Expand All', 'توسيع الكل'),
('expiredSubmissions', 'Expired Submissions', 'العمليات المنتهية'),
('export', 'Export', 'تصدير'),
('exportActionPointsData', 'Export Action Points Data', 'تصدير بيانات نقاط العمل'),
('exportAll', 'Export All', 'تصدير الكل'),
('exportAsCSV', 'Export as CSV', 'تصدير كـ CSV'),
('exportAsExcel', 'Export as Excel', 'تصدير كـ Excel'),
('exportAsPDF', 'Export as PDF', 'تصدير كـ PDF'),
('exportCSV', 'Export CSV', 'تصدير CSV'),
('exportProcesses', 'Export Processes', 'تصدير العمليات'),
('exportShown', 'Export Shown', 'تصدير المعروض'),
('failed', 'Failed', 'راسب'),
('failedToAddComment', 'Failed to add comment', 'فشل إضافة التعليق'),
('failedToAssignQuiz', 'Failed to assign quiz', 'فشل تعيين الاختبار'),
('failedToChangePassword', 'Failed to change password', 'فشل تغيير كلمة المرور'),
('failedToConnectToServer', 'Failed to connect to server', 'فشل الاتصال بالخادم'),
('failedToCreateCategory', 'Failed to create category', 'فشل إنشاء الفئة'),
('failedToCreateCourse', 'Failed to create course', 'فشل إنشاء الدورة'),
('failedToCreateQuiz', 'Failed to create quiz', 'فشل إنشاء الاختبار'),
('failedToDeleteAudit', 'Failed To Delete Audit', 'Failed To Delete Audit'),
('failedToDeleteCategory', 'Failed to delete category', 'فشل حذف الفئة'),
('failedToDeleteCourse', 'Failed to delete course', 'فشل حذف الدورة'),
('failedToDeleteProcess', 'Failed To Delete Process', 'Failed To Delete Process'),
('failedToDiscardDraft', 'Failed To Discard Draft', 'Failed To Discard Draft'),
('failedToLoadAudit', 'Failed To Load Audit', 'Failed To Load Audit'),
('failedToLoadCategories', 'Failed to load categories', 'فشل تحميل الفئات'),
('failedToLoadNoticeboard', 'Failed to load notice board', 'فشل تحميل لوحة الإعلانات'),
('failedToPublishAudit', 'Failed To Publish Audit', 'Failed To Publish Audit'),
('failedToPublishQuiz', 'Failed to publish quiz', 'فشل نشر الاختبار'),
('failedToSaveAssignment', 'Failed To Save Assignment', 'Failed To Save Assignment'),
('failedToSaveAudit', 'Failed To Save Audit', 'Failed To Save Audit'),
('failedToSaveDraft', 'Failed To Save Draft', 'Failed To Save Draft'),
('failedToSubmitAudit', 'Failed To Submit Audit', 'Failed To Submit Audit'),
('failedToUpdateCategory', 'Failed to update category', 'فشل تحديث الفئة'),
('failedToUpdateCourse', 'Failed to update course', 'فشل تحديث الدورة'),
('featurePermissions', 'Feature Permissions', 'صلاحيات الميزات'),
('featureReports', 'Feature Reports', 'تقارير الميزات'),
('featureReportsHubDesc', 'Feature Reports Hub Desc', 'Feature Reports Hub Desc'),
('featureReportsPageDesc', 'Feature Reports Page Desc', 'Feature Reports Page Desc'),
('fieldsSelected', 'fields selected', 'الحقول المحددة'),
('fillAllPasswordFields', 'Please fill all password fields', 'يرجى ملء جميع حقول كلمة المرور'),
('fillInTheDetailsToCreateANewEntity', 'Fill in the details to create a new entity', 'املأ التفاصيل لإنشاء كيان جديد'),
('fillInTheDetailsToCreateANewUserAccount', 'Fill in the details to create a new user account', 'املأ التفاصيل لإنشاء حساب مستخدم جديد'),
('fillMandatoryTags', 'Fill Mandatory Tags', 'Fill Mandatory Tags'),
('filter', 'Filter', 'تصفية'),
('filterBy', 'Filter by', 'تصفية حسب'),
('filterByActivityStatus', 'Filter by Activity Status', 'تصفية حسب حالة النشاط'),
('filterByCategory', 'Filter by Category', 'تصفية حسب الفئة'),
('filterByEmail', 'Filter by email', 'تصفية حسب البريد الإلكتروني'),
('filterByStatus', 'Filter by status', 'تصفية حسب الحالة'),
('filterByTimePeriod', 'Filter by Time Period', 'تصفية حسب الفترة الزمنية'),
('filterProcesses', 'Filter Processes', 'تصفية العمليات'),
('forgotPassword', 'Forgot password?', 'نسيت كلمة المرور؟'),
('formId', 'Form ID', 'معرف النموذج'),
('functional', 'Functional', 'نشط'),
('general', 'General', 'عام'),
('generalSettings', 'General Settings', 'الإعدادات العامة'),
('generateCsr', 'Generate Csr', 'Generate Csr'),
('geoLocationDetails', 'Geo-Location Details', 'تفاصيل الموقع الجغرافي'),
('geoLocationTab', 'Geo Location Tab', 'الموقع الجغرافي'),
('getCcsid', 'Get Ccsid', 'Get Ccsid'),
('getPcsid', 'Get Pcsid', 'Get Pcsid'),
('goHome', 'Go Home', 'الذهاب إلى الرئيسية'),
('high', 'High', 'عالي'),
('home', 'Home', 'الرئيسية'),
('homeNoticeboardSubtitle', 'Important updates from your organization', 'تحديثات مهمة من مؤسستك'),
('hybridActive', 'Active', 'نشط'),
('hybridAddProfile', 'Add Profile', 'إضافة ملف'),
('hybridAddProfileHint', 'Create a hybrid assignee profile column (max {max} profiles).', 'إنشاء عمود ملف مكلف هجين (الحد الأقصى {max} ملفات).'),
('hybridAddProfileTitle', 'Add Profile', 'إضافة ملف'),
('hybridAddProfileToAssign', 'Add a profile column to assign users', 'أضف عمود ملف لتعيين المستخدمين'),
('hybridAddProfileToAssignRow', 'Add a profile to assign users', 'أضف ملفاً لتعيين المستخدمين'),
('hybridAddSelected', 'Add Selected', 'إضافة المحدد'),
('hybridAddStores', 'Add Store(s)', 'إضافة متجر (متاجر)'),
('hybridAddStoresHint', 'Select stores to include in the hybrid assignee matrix.', 'اختر المتاجر لتضمينها في مصفوفة المكلف الهجين.'),
('hybridAddStoresTitle', 'Add Store(s)', 'إضافة متجر (متاجر)'),
('hybridAddStoresToBuild', 'Add store(s) to build the assignment matrix', 'أضف متجراً (متاجر) لبناء مصفوفة التعيين'),
('hybridAllStoresAdded', 'All stores are already added.', 'تمت إضافة جميع المتاجر بالفعل.'),
('hybridAssignee', 'Hybrid Assignee', 'المكلف الهجين'),
('hybridAssigneeDescription', 'Manage stores, profiles, and user assignments for workflow automation.', 'إدارة المتاجر والملفات وتعيينات المستخدمين لأتمتة سير العمل.'),
('hybridAssigneeTitle', 'Hybrid Assignee Profile', 'ملف المكلف الهجين'),
('hybridAssignmentsSaved', 'Assignments saved', 'تم حفظ التعيينات'),
('hybridAssignmentsSaveFailed', 'Failed to save assignments', 'فشل حفظ التعيينات'),
('hybridAssignUsers', 'Assign users', 'تعيين مستخدمين'),
('hybridAssignUsersTitle', 'Assign Users', 'تعيين المستخدمين'),
('hybridConfigured', 'Configured', 'مُعد'),
('hybridCreate', 'Create', 'إنشاء'),
('hybridDeleteProfileConfirm', 'Delete profile "{name}"?', 'حذف الملف "{name}"؟'),
('hybridDraft', 'Draft', 'مسودة'),
('hybridLoadFailed', 'Failed to load hybrid assignee data', 'فشل تحميل بيانات المكلف الهجين'),
('hybridNoStoresMatchSearch', 'No stores match your search', 'لا توجد متاجر تطابق بحثك'),
('hybridNoUsersAvailable', 'No users available', 'لا يوجد مستخدمون متاحون'),
('hybridProfileCreated', 'Profile created', 'تم إنشاء الملف'),
('hybridProfileCreateFailed', 'Failed to create profile', 'فشل إنشاء الملف'),
('hybridProfileDeleted', 'Profile deleted', 'تم حذف الملف'),
('hybridProfileDeleteFailed', 'Failed to delete profile', 'فشل حذف الملف'),
('hybridProfileName', 'Profile Name', 'اسم الملف'),
('hybridProfileNamePlaceholder', 'e.g., Operations Team', 'مثال: فريق العمليات'),
('hybridProfileNameRequired', 'Profile name is required', 'اسم الملف مطلوب'),
('hybridProfilePublished', 'Profile published', 'تم نشر الملف'),
('hybridProfilePublishFailed', 'Failed to publish profile', 'فشل نشر الملف'),
('hybridProfiles', 'Profiles', 'الملفات'),
('hybridProfileUpdated', 'Profile updated', 'تم تحديث الملف'),
('hybridProfileUpdateFailed', 'Failed to update profile', 'فشل تحديث الملف'),
('hybridPublished', 'Published', 'منشور'),
('hybridRemoveStoreConfirm', 'Remove store "{name}" from hybrid assignee?', 'إزالة المتجر "{name}" من المكلف الهجين؟'),
('hybridRenameProfileHint', 'Rename this hybrid assignee profile.', 'إعادة تسمية ملف المكلف الهجين هذا.'),
('hybridSearch', 'Search', 'بحث'),
('hybridSelectStore', 'Select at least one store', 'اختر متجراً واحداً على الأقل'),
('hybridSelectUsersHint', 'Select users for this store and profile.', 'اختر المستخدمين لهذا المتجر والملف.'),
('hybridStoreName', 'Store Name', 'اسم المتجر'),
('hybridStoreRemoved', 'Store removed', 'تمت إزالة المتجر'),
('hybridStoreRemoveFailed', 'Failed to remove store', 'فشلت إزالة المتجر'),
('hybridStores', 'Stores', 'المتاجر'),
('hybridStoresAdded', 'Stores added', 'تمت إضافة المتاجر'),
('hybridStoresAddFailed', 'Failed to add stores', 'فشلت إضافة المتاجر'),
('hybridTotalAssignments', 'Total Assignments', 'إجمالي التعيينات'),
('hybridUsers', 'Users', 'المستخدمون'),
('image', 'Image', 'Image'),
('inactive', 'Inactive', 'غير نشط'),
('inAppNotifications', 'In-App Notifications', 'إشعارات داخل التطبيق'),
('inAppNotificationsDisabled', 'In-app notifications are turned off. Enable them above to configure types.', 'إشعارات داخل التطبيق متوقفة. فعّلها أعلاه لتكوين الأنواع.'),
('inAppNotificationsHint', 'Show alerts inside the application', 'عرض التنبيهات داخل التطبيق'),
('inAppNotificationTypes', 'In-app notification types', 'أنواع الإشعارات داخل التطبيق'),
('inAppNotificationTypesHint', 'Turn off specific in-app alerts while keeping others enabled.', 'أوقف تنبيهاً محدداً داخل التطبيق مع إبقاء الأنواع الأخرى مفعّلة.'),
('inProgress', 'In Progress', 'قيد التنفيذ'),
('instantAlerts', 'Instant', 'فوري'),
('invalid', 'Invalid', 'غير صالح'),
('invalidEmailOrPassword', 'Invalid email or password', 'البريد الإلكتروني أو كلمة المرور غير صحيحة'),
('issueTickets', 'Issue Tickets', 'تذاكر المشكلات'),
('items', 'items', 'عناصر'),
('itHelpdesk', 'IT Helpdesk', 'مكتب المساعدة التقني'),
('language', 'Language', 'اللغة'),
('lastLogin', 'Last Login', 'آخر تسجيل دخول'),
('lastUpdatedAt', 'Last updated at', 'آخر تحديث في'),
('lastUpdatedToday', 'Last updated: Today', 'آخر تحديث: اليوم'),
('late', 'Late', 'متأخر'),
('latitude', 'Latitude', 'خط العرض'),
('latitudeMustBeBetween', 'latitude must be between -90 and 90', 'يجب أن يكون خط العرض بين -90 و 90'),
('latitudeRangeHint', 'Latitude Range Hint', 'Latitude Range Hint'),
('learning', 'Learning', 'التعلم'),
('learningAssignments', 'Course & assessment assignments', 'تعيينات الدورات والتقييمات'),
('learningNotifications', 'Learning Notifications', 'إشعارات التعلم'),
('learningNotificationsHint', 'Control alerts for course assignments and certificate issuance when you complete learning.', 'تحكم في تنبيهات تعيينات الدورات وإصدار الشهادات عند إكمال التعلم.'),
('learningReports', 'Learning Reports', 'تقارير التعلم'),
('learningReportsDesc', 'Monitor course completion, learner progress, assessments, and training compliance.', 'مراقبة إكمال الدورات وتقدم المتعلمين والتقييمات والامتثال للتدريب.'),
('loading', 'Loading...', 'جاري التحميل...'),
('loadingAudit', 'Loading Audit', 'Loading Audit'),
('loadingCategoriesAndCourses', 'Loading categories and courses...', 'جاري تحميل الفئات والدورات...'),
('loadingCities', 'Loading cities...', 'جاري تحميل المدن...'),
('loadingDistricts', 'Loading districts...', 'جاري تحميل الأحياء...'),
('loadingNoticeboard', 'Loading notices…', 'جارٍ تحميل الإشعارات…'),
('loadingQuizzes', 'Loading quizzes...', 'جاري تحميل الاختبارات...'),
('loadingRegions', 'Loading regions...', 'جاري تحميل المناطق...'),
('loadingUsers', 'Loading users…', 'جاري تحميل المستخدمين…'),
('loadMore', 'Load More', 'تحميل المزيد'),
('loadMoreActionPoints', 'Load More Action Points', 'تحميل المزيد من نقاط العمل'),
('locationDataUnavailable', 'Location list is unavailable. You can still create the entity without it.', 'قائمة المواقع غير متاحة. يمكنك إنشاء الكيان بدونها.'),
('locationOptionalHint', 'Optional — you can add region, city, and district later.', 'اختياري — يمكنك إضافة المنطقة والمدينة والحي لاحقاً.'),
('locationSaudiNationalAddress', 'Location Saudi National Address', 'Location Saudi National Address'),
('loginToManageNotifications', 'Sign in to manage your notification preferences.', 'سجّل الدخول لإدارة تفضيلات الإشعارات.'),
('logout', 'Logout', 'تسجيل الخروج'),
('longitude', 'Longitude', 'خط الطول'),
('longitudeMustBeBetween', 'longitude must be between -180 and 180', 'يجب أن يكون خط الطول بين -180 و 180'),
('longitudeRangeHint', 'Longitude Range Hint', 'Longitude Range Hint'),
('low', 'Low', 'منخفض'),
('manageAnnouncementsAndUpdates', 'Manage announcements and updates', 'إدارة الإعلانات والتحديثات'),
('manageBusinessEntitiesAndLocations', 'Manage business entities and locations', 'إدارة الكيانات والمواقع التجارية'),
('manageCategories', 'Manage categories and courses', 'إدارة الفئات والدورات'),
('management', 'Management', 'الإدارة'),
('manageNotificationPreferences', 'Manage notification preferences', 'إدارة تفضيلات الإشعارات'),
('manageProcessesAndAudits', 'Manage and monitor your processes and audits', 'إدارة ومتابعة العمليات والتدقيق'),
('manager', 'Manager', 'المدير'),
('manageTags', 'Manage Tags', 'إدارة العلامات'),
('mandatory', 'Mandatory', 'إلزامي'),
('markComplete', 'Mark Complete', 'تحديد كمكتمل'),
('maxFieldsSelected', 'Max Fields Selected', 'Max Fields Selected'),
('mediaTypeOptional', 'Media Type (Optional)', 'نوع الوسائط (اختياري)'),
('mediaUrlOptional', 'Media URL (Optional)', 'رابط الوسائط (اختياري)'),
('medium', 'Medium', 'متوسط'),
('member', 'member', 'عضو'),
('members', 'Members', 'الأعضاء'),
('membersPlural', 'members', 'أعضاء'),
('mentions', 'Mentions', 'الإشارات'),
('mobileAlerts', 'Mobile alerts', 'تنبيهات الجوال'),
('moreFilters', 'More Filters', 'المزيد من الفلاتر'),
('moreInfoAbout', 'More info about', 'مزيد من المعلومات حول'),
('multipleAnswer', 'Multiple Answers', 'إجابات متعددة'),
('myProfile', 'My Profile', 'ملفي الشخصي'),
('myReport', 'My Report', 'تقريري'),
('myTasks', 'My Tasks', 'مهامي'),
('name', 'Name', 'الاسم'),
('nameAsc', 'Name (ASC)', 'الاسم (تصاعدي)'),
('nameDesc', 'Name (DESC)', 'الاسم (تنازلي)'),
('new', 'New', 'New'),
('newActionPoint', 'New Action Point', 'نقطة عمل جديدة'),
('newAudit', 'New Audit', 'New Audit'),
('newEntity', 'New Entity', 'كيان جديد'),
('newPassword', 'New Password', 'كلمة المرور الجديدة'),
('newPasswordMustDiffer', 'New password must be different from the current password', 'يجب أن تختلف كلمة المرور الجديدة عن الحالية'),
('newPost', 'New Post', 'منشور جديد'),
('newUser', 'New User', 'مستخدم جديد'),
('no', 'No', 'لا'),
('noActionPointsAvailable', 'No action points available for this date range. Try selecting a different date range :)', 'لا توجد نقاط عمل متاحة لهذه الفترة الزمنية. حاول اختيار فترة زمنية مختلفة :)'),
('noApprovalsMatchCriteria', 'No approvals match your criteria.', 'لا توجد موافقات تطابق معاييرك.'),
('noAssignedAudits', 'No Assigned Audits', 'No Assigned Audits'),
('noAssigneeProfilesAvailable', 'No assignee profiles available', 'لا توجد ملفات تعيين المكلفين'),
('noAuditsYet', 'No Audits Yet', 'No Audits Yet'),
('noAuditTagsYet', 'No Audit Tags Yet', 'No Audit Tags Yet'),
('noCategoriesOrCoursesFound', 'No categories or courses found', 'لم يتم العثور على فئات أو دورات'),
('noCommentsYet', 'No comments yet', 'لا توجد تعليقات بعد'),
('noCoursesInThisCategory', 'No courses in this category', 'لا توجد دورات في هذه الفئة'),
('noData', 'No data', 'لا توجد بيانات'),
('noDataAvailable', 'No data available', 'لا توجد بيانات متاحة'),
('noDataFound', 'No data found', 'لم يتم العثور على بيانات'),
('noDescription', 'No description', 'لا يوجد وصف'),
('noDesignationsAvailable', 'No designations available', 'لا يوجد مسميات وظيفية متاحة'),
('noDueDate', 'No due date', 'لا يوجد تاريخ استحقاق'),
('noEmailOnProfile', 'Add email in your profile', 'أضف البريد الإلكتروني في ملفك الشخصي'),
('noEntitiesAvailable', 'No entities available', 'لا توجد كيانات متاحة'),
('none', 'None', 'لا شيء'),
('nonFunctional', 'Non-Functional', 'غير نشط'),
('noNoticeboardPostsAvailable', 'No noticeboard posts available', 'لا توجد منشورات في لوحة الإعلانات'),
('noNotificationsYet', 'No notifications yet', 'لا توجد إشعارات بعد'),
('noPendingTasksInQueue', 'No pending tasks for this day', 'لا توجد مهام معلقة لهذا اليوم'),
('noProcessesAvailable', 'No processes available', 'لا توجد عمليات متاحة'),
('noProcessesMatchCriteria', 'No processes match your criteria.', 'لا توجد عمليات تطابق معاييرك.'),
('noQuizzesFound', 'No quizzes found', 'لم يتم العثور على اختبارات'),
('noRecentActivity', 'No Recent Activity', 'No Recent Activity'),
('noRecord', 'No record', 'لا يوجد سجل'),
('noRemovedEntities', 'No removed entities', 'لا توجد كيانات محذوفة'),
('noRemovedUsers', 'No Removed Users', 'No Removed Users'),
('noStoresAssigned', 'No stores assigned to this profile', 'لا توجد متاجر معينة لهذا الملف التعريفي'),
('noStoresFound', 'No Stores Found', 'No Stores Found'),
('noTagsAvailableCreateInTagsTab', 'No Tags Available Create In Tags Tab', 'No Tags Available Create In Tags Tab'),
('noTasksAvailableDateRange', 'No Tasks available for this date range. Try selecting a different date range :)', 'لا توجد مهام متاحة لهذه الفترة الزمنية. حاول اختيار فترة زمنية مختلفة :)'),
('notAvailable', 'N/A', 'غير متاح'),
('noticeboard', 'Noticeboard', 'لوحة الإعلانات'),
('noticeBoard', 'Notice Board', 'لوحة الإعلانات'),
('noticeboardEmptyHint', 'Active posts created in Manage Notice Board will appear here.', 'ستظهر هنا المنشورات النشطة التي يتم إنشاؤها من إدارة لوحة الإعلانات.'),
('notificationPreferences', 'Notification Preferences', 'تفضيلات الإشعارات'),
('notificationPreferencesSummary', 'Your notification preferences', 'تفضيلات الإشعارات الخاصة بك'),
('notifications', 'Notifications', 'الإشعارات'),
('notificationSettings', 'Notification Settings', 'إعدادات الإشعارات'),
('notificationSettingsSaved', 'Notification settings saved', 'تم حفظ إعدادات الإشعارات'),
('noUsersAvailable', 'No users available', 'لا يوجد مستخدمون'),
('noUsersFound', 'No Users Found', 'No Users Found'),
('noUserTeamsAvailable', 'No user teams available', 'لا توجد فرق مستخدمين'),
('noWorkflowsMatchCriteria', 'No workflows match your criteria.', 'لا يوجد سير عمل يطابق معاييرك.'),
('off', 'Off', 'إيقاف'),
('on', 'On', 'تشغيل'),
('oneDay', '1 day', 'يوم واحد'),
('onHold', 'On Hold', 'معلق'),
('onTime', 'On Time', 'في الوقت'),
('open', 'Open', 'مفتوح'),
('openSection', 'Open Section', 'Open Section'),
('or', 'or', 'أو'),
('organizationReport', 'Organization Report', 'تقرير المنظمة'),
('organizationReportDesc', 'Organization-wide process and audit submissions', 'إرسالات العمليات والتدقيق على مستوى المنظمة'),
('organizeAndAutomateActionsWithTags', 'Organize and automate actions with tags', 'تنظيم وأتمتة الإجراءات باستخدام العلامات'),
('overdue', 'Overdue', 'متأخر'),
('owner', 'Owner', 'Owner'),
('ownerName', 'Owner Name', 'اسم المالك'),
('pageMayHaveBeenMovedOrDeleted', 'The page may have been moved or deleted.', 'قد تكون الصفحة تم نقلها أو حذفها.'),
('pageNotFound', 'Page Not Found', 'الصفحة غير موجودة'),
('passed', 'Passed', 'ناجح'),
('passing', 'Passing', 'Passing'),
('passingScorePercent', 'Passing Score (%)', 'درجة النجاح (%)'),
('passThreshold', 'Pass Threshold', 'Pass Threshold'),
('password', 'Password', 'كلمة المرور'),
('passwordChangedSuccessfully', 'Password changed successfully', 'تم تغيير كلمة المرور بنجاح'),
('passwordPolicyHint', 'Password must be at least 8 characters and include 1 lowercase letter, 1 number, and 1 special character', 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتتضمن حرفًا صغيرًا ورقمًا ورمزًا خاصًا'),
('passwordsDoNotMatch', 'Passwords do not match', 'كلمتا المرور غير متطابقتين'),
('pcsidRetrievedPreview', 'Pcsid Retrieved Preview', 'Pcsid Retrieved Preview'),
('pending', 'Pending', 'قيد الانتظار'),
('period', 'Period', 'Period'),
('permissions', 'Permissions', 'الأذونات'),
('perPage', '/ page', '/ صفحة'),
('phoneNumber', 'Phone Number', 'رقم الهاتف'),
('pickADate', 'Pick a date', 'اختر تاريخ'),
('platformName', 'Platform Name', 'اسم المنصة'),
('platformSettings', 'Platform Settings', 'إعدادات المنصة'),
('pleaseEnterDetailsSignIn', 'Please enter your details to sign in', 'يرجى إدخال بياناتك لتسجيل الدخول'),
('pleaseLoginToChangePassword', 'You must be logged in to change your password', 'يجب تسجيل الدخول لتغيير كلمة المرور'),
('pleaseLoginToComment', 'Please log in to comment', 'يرجى تسجيل الدخول للتعليق'),
('pleaseLoginToLike', 'Please log in to like posts', 'يرجى تسجيل الدخول للإعجاب'),
('pleaseSelectACategory', 'Please Select A Category', 'Please Select A Category'),
('pleaseSelectFileToUpload', 'Please Select File To Upload', 'Please Select File To Upload'),
('postComment', 'Post', 'نشر'),
('present', 'Present', 'حاضر'),
('priority', 'Priority', 'الأولوية'),
('process', 'Process', 'Process'),
('processAndWorkflow', 'Process and Workflow', 'العمليات وسير العمل'),
('processAssignment', 'Process Assignment', 'تعيين العملية'),
('processes', 'Processes', 'عمليات'),
('processManagement', 'Process Management', 'إدارة العمليات'),
('processReport', 'Process Report', 'تقرير العملية'),
('processReports', 'Process Reports', 'تقارير العمليات'),
('processReportsDesc', 'Analyze process completion, compliance, and multi-level performance.', 'تحليل إكمال العمليات والامتثال والأداء متعدد المستويات.'),
('processTab', 'Processes', 'العمليات'),
('processTag', 'Process Tag', 'علامة العملية'),
('profileName', 'Profile Name', 'Profile Name'),
('profileSettings', 'Profile Settings', 'إعدادات الملف الشخصي'),
('publish', 'Publish', 'نشر'),
('publishAfterBuildPropertiesAndAssign', 'Publish After Build Properties And Assign', 'Publish After Build Properties And Assign'),
('publishAudit', 'Publish Audit', 'Publish Audit'),
('published', 'Published', 'منشور'),
('publishingQuizConfirmation', 'Publishing this quiz will make it available to assigned users. Are you sure you want to publish?', 'نشر هذا الاختبار سيجعله متاحًا للمستخدمين المعينين. هل أنت متأكد أنك تريد النشر؟'),
('publishQuiz', 'Publish Quiz', 'نشر الاختبار'),
('purposeOfReports', 'Purpose Of Reports', 'Purpose Of Reports'),
('pushNotifications', 'Push Notifications', 'الإشعارات الفورية'),
('pushNotificationTypes', 'Push notification types', 'أنواع إشعارات الدفع'),
('pushNotificationTypesHint', 'Choose which updates trigger push alerts on your devices.', 'اختر التحديثات التي تُرسل تنبيهات دفع إلى أجهزتك.'),
('putOnHold', 'Put on Hold', 'وضع في الانتظار'),
('questionTag', 'Question Tag', 'علامة السؤال'),
('quizAssignedSuccessfully', 'Quiz assigned successfully', 'تم تعيين الاختبار بنجاح'),
('quizCreatedSuccessfully', 'Quiz created successfully', 'تم إنشاء الاختبار بنجاح'),
('quizPublishedSuccessfully', 'Quiz published successfully', 'تم نشر الاختبار بنجاح'),
('quizTitle', 'Quiz Title', 'عنوان الاختبار'),
('quizTitleIsRequired', 'Quiz title is required', 'عنوان الاختبار مطلوب'),
('raiseActionPoint', 'Raise Action Point', 'رفع نقطة عمل'),
('records', 'records', 'سجلات'),
('refresh', 'Refresh', 'تحديث'),
('refreshProcesses', 'Refresh Processes', 'تحديث العمليات'),
('region', 'Region', 'المنطقة'),
('regionalManagers', 'Regional Managers', 'Regional Managers'),
('registerDeviceTab', 'Register Device Tab', 'تسجيل الجهاز'),
('rejected', 'Rejected', 'مرفوض'),
('rememberMe', 'Remember me', 'تذكرني'),
('remove', 'Remove', 'إزالة'),
('removedAt', 'Removed At', 'تم الحذف في'),
('removedEntity', 'Removed Entity', 'الكيان المحذوف'),
('removedUser', 'Removed User', 'المستخدم المحذوف'),
('reportAccessTip', 'Report Access Tip', 'Report Access Tip'),
('reportAccessTipTitle', 'Report Access Tip Title', 'Report Access Tip Title'),
('reportingAndInsights', 'Reporting & Insights', 'التقارير والرؤى'),
('reportingAndInsightsIntro', 'Access reports, dashboards, and analytics across your organization.', 'الوصول إلى التقارير ولوحات المعلومات والتحليلات عبر مؤسستك.'),
('reportingDesignation', 'Reporting Designation', 'المسمى الوظيفي التقريري'),
('reportPurposeActionable', 'Report Purpose Actionable', 'Report Purpose Actionable'),
('reportPurposeCompliance', 'Report Purpose Compliance', 'Report Purpose Compliance'),
('reportPurposeDecisions', 'Report Purpose Decisions', 'Report Purpose Decisions'),
('reportPurposeVisibility', 'Report Purpose Visibility', 'Report Purpose Visibility'),
('reports', 'Reports', 'التقارير'),
('requiredColumns', 'Required Columns', 'الأعمدة المطلوبة'),
('reset', 'Reset', 'إعادة تعيين'),
('resetFilters', 'Reset Filters', 'إعادة تعيين الفلاتر'),
('rootTagName', 'Root Tag Name', 'اسم العلامة الجذرية'),
('save', 'Save', 'حفظ'),
('saveAllSettings', 'Save All Settings', 'حفظ جميع الإعدادات'),
('saveAssignment', 'Save Assignment', 'Save Assignment'),
('saveChanges', 'Save Changes', 'حفظ التغييرات'),
('saveConfiguration', 'Save Configuration', 'حفظ الإعدادات'),
('saveDraft', 'Save Draft', 'Save Draft'),
('savePreferences', 'Save Preferences', 'حفظ التفضيلات'),
('saveProfile', 'Save Profile', 'حفظ الملف التعريفي'),
('saveSettings', 'Save settings', 'حفظ الإعدادات'),
('schedule', 'Schedule', 'الجدول'),
('search', 'Search', 'بحث'),
('searchActionPoints', 'Search Action Points', 'البحث عن نقاط العمل'),
('searchApprovals', 'Search Approvals', 'البحث عن الموافقات'),
('searchAudit', 'Search Audit', 'بحث التدقيق'),
('searchByName', 'Search by name', 'البحث بالاسم'),
('searchEntity', 'Search Entity', 'بحث الكيان'),
('searchPosts', 'Search Posts', 'البحث في المنشورات'),
('searchProcess', 'Search Process', 'بحث عملية'),
('searchProcesses', 'Search Processes', 'البحث عن العمليات'),
('searchProcessesByKeyword', 'Search processes by keyword', 'البحث عن العمليات بالكلمة المفتاحية'),
('searchReports', 'Search Reports', 'Search Reports'),
('searchStores', 'Search stores', 'بحث في المتاجر'),
('searchSubmissions', 'Search submissions...', 'بحث في الإرسالات...'),
('searchTags', 'Search Tags', 'بحث العلامات'),
('searchUsers', 'Search users', 'بحث في المستخدمين'),
('searchWorkflows', 'Search Workflows', 'البحث عن سير العمل'),
('security', 'Security', 'الأمان'),
('seeAll', 'See All', 'عرض الكل'),
('select', 'Select', 'اختيار'),
('selectAll', 'Select All', 'اختيار الكل'),
('selectAnOption', 'Select An Option', 'Select An Option'),
('selectAssignee', 'Select Assignee', 'Select Assignee'),
('selectCategory', 'Select Category', 'اختر الفئة'),
('selectCity', 'Select city', 'اختر المدينة'),
('selectCityFirst', 'Select city first', 'اختر المدينة أولاً'),
('selectDate', 'Select Date', 'اختر تاريخ'),
('selectDesignation', 'Select Designation', 'اختر المسمى الوظيفي'),
('selectDistrict', 'Select district', 'اختر الحي'),
('selectedStoresCount', 'Selected Stores Count', 'Selected Stores Count'),
('selectedUsersCount', 'Selected Users Count', 'Selected Users Count'),
('selectEntity', 'Select Entity', 'اختر الكيان'),
('selectFieldsToDisplayInTheUserTable', 'Select Fields To Display In The User Table', 'Select Fields To Display In The User Table'),
('selectHierarchyUser', 'Select a user from the hierarchy to view details', 'اختر مستخدماً من التسلسل الهرمي لعرض التفاصيل'),
('selectManager', 'Select Manager', 'اختر المدير'),
('selectMediaType', 'Select media type', 'اختر نوع الوسائط'),
('selectOwner', 'Select owner', 'اختر المالك'),
('selectProcess', 'Select Process', 'اختر العملية'),
('selectRegion', 'Select region', 'اختر المنطقة'),
('selectRegionFirst', 'Select region first', 'اختر المنطقة أولاً'),
('selectReportingDesignation', 'Select reporting designation', 'اختر المسمى الوظيفي التقريري'),
('selectStore', 'Select store...', 'اختر المتجر...'),
('selectStoreLocationFirst', 'Select Store Location First', 'Select Store Location First'),
('selectStores', 'Select Stores', 'اختيار المتاجر'),
('selectStoreStatus', 'Select Store Status', 'Select Store Status'),
('selectSystemRole', 'Select system role', 'اختر الدور النظامي'),
('selectTag', 'Select Tag', 'Select Tag'),
('selectUpTo8FieldsToDisplayInTheEntityTable', 'Select up to 8 fields to display in the entity table', 'حدد حتى 8 حقول لعرضها في جدول الكيانات'),
('selectUserOrStoreToAssign', 'Select User Or Store To Assign', 'Select User Or Store To Assign'),
('selectUsers', 'Select Users', 'اختيار المستخدمين'),
('selectUserTagColumnsToDisplay', 'Select User Tag Columns To Display', 'Select User Tag Columns To Display'),
('sessionTimeout', 'Session Timeout', 'انتهاء الجلسة'),
('settings', 'Settings', 'الإعدادات'),
('shortAnswer', 'Short Answer', 'إجابة قصيرة'),
('signIn', 'Sign in', 'تسجيل الدخول'),
('signingIn', 'Signing in...', 'جاري تسجيل الدخول...'),
('singleAnswer', 'Single Answer', 'إجابة واحدة'),
('smsNotifications', 'SMS Notifications', 'إشعارات الرسائل النصية'),
('sorryPageDoesntExist', 'Sorry, the page you are looking for does not exist.', 'عذراً، الصفحة التي تبحث عنها غير موجودة.'),
('sortBy', 'Sort by', 'ترتيب حسب'),
('sortProcesses', 'Sort Processes', 'ترتيب العمليات'),
('soundAlerts', 'Sound alerts', 'تنبيهات صوتية'),
('staff', 'Staff', 'الموظفون'),
('staffCount', 'Staff Count', 'Staff Count'),
('standardReports', 'Standard Reports', 'التقارير القياسية'),
('standardReportsHubDesc', 'Standard Reports Hub Desc', 'Standard Reports Hub Desc'),
('start', 'Start', 'Start'),
('startProgress', 'Start Progress', 'بدء التقدم'),
('status', 'Status', 'الحالة'),
('statusDistribution', 'Status Distribution', 'توزيع الحالة'),
('storeHealthCompliance', 'Store Health & Compliance', 'صحة المتجر والامتثال'),
('storeHealthComplianceDesc', 'Executive view of store compliance and health metrics.', 'عرض تنفيذي لمقاييس امتثال وصحة المتجر.'),
('storeManagers', 'Store Managers', 'Store Managers'),
('storeName', 'Store Name', 'اسم المتجر'),
('storeNameAndEntityIdRequired', 'Store Name And Entity Id Required', 'Store Name And Entity Id Required'),
('storeRadiusMeters', 'Store Radius (meters)', 'نصف قطر المتجر (متر)'),
('storeRadiusMustBeBetween', 'store radius must be between 100 meters and 1000 meters. default : 100m', 'يجب أن يكون نصف قطر المتجر بين 100 متر و 1000 متر. الافتراضي: 100 متر'),
('storeRadiusRangeHint', 'Store Radius Range Hint', 'Store Radius Range Hint'),
('storeReport', 'Store Report', 'تقرير المتجر'),
('storeReportDesc', 'Store-level process and audit submissions', 'إرسالات العمليات والتدقيق على مستوى المتجر'),
('stores', 'Stores', 'المتاجر'),
('storesAssignedToProfile', 'Stores assigned to {{profileName}}', 'المتاجر المعينة لـ {{profileName}}'),
('storeStatus', 'Store Status', 'حالة المتجر'),
('storesUnderCoverage', 'Stores under coverage', 'المتاجر ضمن نطاق التغطية'),
('streamlineBusinessOperations', 'Streamline your business operations with our comprehensive management platform. Track compliance, manage teams, and optimize workflows all in one place.', 'تبسيط عمليات عملك مع منصة الإدارة الشاملة الخاصة بنا. تتبع الامتثال، وإدارة الفرق، وتحسين سير العمل كل في مكان واحد.'),
('streetName', 'Street name', 'اسم الشارع'),
('submissionsByDate', 'Submissions by Date', 'الإرسالات حسب التاريخ'),
('submissionsByStore', 'Submissions by Store', 'الإرسالات حسب المتجر'),
('submit', 'Submit', 'إرسال'),
('submitForFutureOrPastDates', 'Submit For Future Or Past Dates', 'Submit For Future Or Past Dates'),
('summaryAnalytics', 'Summary Analytics', 'التحليلات الملخصة'),
('summaryAnalyticsContentComingSoon', 'Summary Analytics Content Coming Soon', 'محتوى التحليلات الملخصة قادم قريباً'),
('syncingAuditDraft', 'Syncing Audit Draft', 'Syncing Audit Draft'),
('systemRole', 'System Role', 'الدور النظامي'),
('tabContentComingSoon', 'tab content coming soon...', 'محتوى التبويب قادم قريباً...'),
('tag', 'Tag', 'العلامة'),
('tagName', 'Tag Name', 'اسم العلامة'),
('tagReport', 'Tag Report', 'تقرير العلامات'),
('tags', 'Tags', 'العلامات'),
('tagsCreated', 'Tags Created', 'العلامات المنشأة'),
('tagsTab', 'Tags Tab', 'العلامات'),
('tagValue', 'Tag Value', 'قيمة العلامة'),
('tagValues', 'Tag Values', 'قيم العلامة'),
('taskReminders', 'Task Reminders', 'تذكيرات المهام'),
('tasks', 'Tasks', 'المهام'),
('tasksInQueue', 'Tasks in Queue', 'المهام في قائمة الانتظار'),
('team', 'Team', 'الفريق'),
('teamName', 'Team Name', 'اسم الفريق'),
('teamNamePlaceholder', 'e.g., East Zonal Team, Store Ops Leads', 'مثال: فريق المنطقة الشرقية، قادة عمليات المتجر'),
('templateNameOptional', 'Dashboard name (optional)', 'اسم لوحة المعلومات (اختياري)'),
('thisMonth', 'This Month', 'هذا الشهر'),
('thisWeek', 'This Week', 'هذا الأسبوع'),
('ticket', 'Ticket', 'تذكرة'),
('ticketReports', 'Ticket Reports', 'تقارير التذاكر'),
('ticketReportsDesc', 'Track ticket status, resolution time, categories, and vendor/assignee performance.', 'تتبع حالة التذاكر ووقت الحل والفئات وأداء الموردين والمكلفين.'),
('time', 'Time', 'الوقت'),
('timeLeft', 'Time Left', 'الوقت المتبقي'),
('timeLimit', 'Time Limit (minutes)', 'الحد الزمني (دقائق)'),
('timezone', 'Timezone', 'المنطقة الزمنية'),
('title', 'Title', 'العنوان'),
('to', 'To', 'To'),
('today', 'Today', 'اليوم'),
('total', 'Total', 'إجمالي'),
('totalActionPoints', 'Total Action Points', 'إجمالي نقاط العمل'),
('totalEntity', 'Total Entity', 'إجمالي الكيانات'),
('totalSubmissions', 'Total Submissions', 'إجمالي الإرسالات'),
('totalUsers', 'Total Users', 'إجمالي المستخدمين'),
('trackAndManage', 'Track and manage all store-level assets', 'تتبع وإدارة جميع أصول المتجر'),
('trainersAndHr', 'Trainers And Hr', 'Trainers And Hr'),
('tryAgain', 'Try again', 'حاول مرة أخرى'),
('twoFactorAuthentication', 'Two-Factor Authentication', 'المصادقة الثنائية'),
('unitedStates', 'United States', 'الولايات المتحدة'),
('unknown', 'Unknown', 'غير معروف'),
('unknownStore', 'Unknown store', 'متجر غير معروف'),
('unknownUser', 'Unknown user', 'مستخدم غير معروف'),
('unsavedChanges', 'Unsaved', 'غير محفوظ'),
('unsavedNotificationChanges', 'You have unsaved notification preference changes.', 'لديك تغييرات غير محفوظة في تفضيلات الإشعارات.'),
('updateAssigneeProfile', 'Update the assignee profile details', 'تحديث تفاصيل ملف تعيين المكلف'),
('updateDropdownTagWithMultipleValues', 'Update Dropdown Tag With Multiple Values', 'Update Dropdown Tag With Multiple Values'),
('updateEntity', 'Update Entity', 'تحديث الكيان'),
('updateEntityDetails', 'Update the entity details', 'تحديث تفاصيل الكيان'),
('updateNoticeboardPostDetails', 'Update noticeboard post details.', 'تحديث تفاصيل منشور لوحة الإعلانات.'),
('updatePassword', 'Update Password', 'تحديث كلمة المرور'),
('updatePost', 'Update Post', 'تحديث المنشور'),
('updateTag', 'Update Tag', 'تحديث العلامة'),
('updateTeam', 'Update Team', 'تحديث الفريق'),
('updateTheTagDetails', 'Update the tag details', 'تحديث تفاصيل العلامة'),
('updateUser', 'Update User', 'تحديث المستخدم'),
('updateUserDetailsManagerIsRequiredWhenEditing', 'Update user details. Manager is required when editing.', 'تحديث تفاصيل المستخدم. المدير مطلوب عند التعديل.'),
('upload', 'Upload', 'Upload'),
('uploadFile', 'Upload File', 'تحميل ملف'),
('uploadUsers', 'Upload Users', 'رفع المستخدمين'),
('urgentMessagesOnly', 'Urgent messages only', 'الرسائل العاجلة فقط'),
('urgentOnly', 'Urgent only', 'العاجل فقط'),
('urlQr', 'Url Qr', 'Url Qr'),
('userDetails', 'User Details', 'تفاصيل المستخدم'),
('userHierarchy', 'User Hierarchy', 'التسلسل الهرمي للمستخدمين'),
('userManagement', 'User Management', 'إدارة المستخدمين'),
('users', 'Users', 'المستخدمون'),
('userTags', 'User Tags', 'علامات المستخدم'),
('useTemplate', 'Use Template', 'استخدام القالب'),
('valid', 'Valid', 'صالح'),
('validEmail', 'Valid Email', 'البريد الإلكتروني الصالح'),
('validEmails', 'Valid Emails', 'البريد الإلكتروني الصالح'),
('video', 'Video', 'Video'),
('view', 'View', 'عرض'),
('viewActivityOverview', 'View Activity Overview', 'عرض نظرة عامة على النشاط'),
('viewAndManageActionPointDetails', 'View and manage action point details.', 'عرض وإدارة تفاصيل نقطة العمل.'),
('viewCustomReports', 'View Custom Reports', 'عرض التقارير المخصصة'),
('viewDashboard', 'View Dashboard', 'عرض لوحة المعلومات'),
('viewDetails', 'View Details', 'عرض التفاصيل'),
('viewSummaryAnalytics', 'View Summary Analytics', 'عرض التحليلات الملخصة'),
('visualReport', 'Visual Report', 'التقرير المرئي'),
('visualReportDesc', 'Visual analytics and insights', 'تحليلات ورؤى مرئية'),
('weeklyDigest', 'Weekly Digest', 'الملخص الأسبوعي'),
('welcomeBack', 'Welcome back', 'مرحباً بعودتك'),
('workflowStatusTab', 'Workflow Status', 'حالة سير العمل'),
('workflowTypeDistribution', 'Workflow Type Distribution', 'توزيع نوع سير العمل'),
('writeAComment', 'Write a comment', 'اكتب تعليقاً'),
('yes', 'Yes', 'نعم'),
('yourFileMustIncludeTheseColumns', 'Your file must include these columns', 'يجب أن يحتوي ملفك على هذه الأعمدة')
ON CONFLICT (key) DO UPDATE SET
  en = EXCLUDED.en,
  ar = EXCLUDED.ar,
  updated_at = CURRENT_TIMESTAMP;
