-- Seed language entries from client/src/i18n.ts fallbackTranslations
-- Generated automatically from TypeScript fallbackTranslations object

CREATE SCHEMA IF NOT EXISTS hashibasha_language;

CREATE TABLE IF NOT EXISTS hashibasha_language.language_entries (
    id SERIAL PRIMARY KEY,
    key VARCHAR(255) UNIQUE NOT NULL,
    en TEXT NOT NULL,
    ar TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO hashibasha_language.language_entries (key, en, ar) VALUES
('manageProcessesAndAudits', 'Manage and monitor your processes and audits', 'إدارة ومتابعة العمليات والتدقيق'),
('assessments', 'Assessments', 'التقييمات'),
('activityOverview', 'Activity Overview', 'نظرة عامة على النشاط'),
('viewActivityOverview', 'View Activity Overview', 'عرض نظرة عامة على النشاط'),
('summaryAnalytics', 'Summary Analytics', 'التحليلات الملخصة'),
('viewSummaryAnalytics', 'View Summary Analytics', 'عرض التحليلات الملخصة'),
('customReports', 'Custom Reports', 'التقارير المخصصة'),
('viewCustomReports', 'View Custom Reports', 'عرض التقارير المخصصة'),
('processAndWorkflow', 'Process and Workflow', 'العمليات وسير العمل'),
('actionPoint', 'Action Point', 'نقطة العمل'),
('learning', 'Learning', 'التعلم'),
('ticket', 'Ticket', 'تذكرة'),
('moreInfoAbout', 'More info about', 'مزيد من المعلومات حول'),
('pending', 'Pending', 'قيد الانتظار'),
('inProgress', 'In Progress', 'قيد التنفيذ'),
('completed', 'Completed', 'مكتمل'),
('assigned', 'Assigned', 'مسند'),
('tasksInQueue', 'Tasks in Queue', 'المهام في قائمة الانتظار'),
('seeAll', 'See All', 'عرض الكل'),
('viewAllTasksInQueue', 'View All Tasks in Queue', 'عرض جميع المهام في قائمة الانتظار'),
('previousDates', 'Previous Dates', 'التواريخ السابقة'),
('nextDates', 'Next Dates', 'التواريخ التالية'),
('viewTaskDetails', 'View Task Details', 'عرض تفاصيل المهمة'),
('noticeBoard', 'Notice Board', 'لوحة الإعلانات'),
('viewAllNotices', 'View All Notices', 'عرض جميع الإشعارات'),
('homeNoticeboardSubtitle', 'Important updates from your organization', 'تحديثات مهمة من مؤسستك'),
('loadingNoticeboard', 'Loading notices…', 'جارٍ تحميل الإشعارات…'),
('failedToLoadNoticeboard', 'Failed to load notice board', 'فشل تحميل لوحة الإعلانات'),
('noNoticeboardPostsAvailable', 'No noticeboard posts available', 'لا توجد منشورات في لوحة الإعلانات'),
('noticeboardEmptyHint', 'Active posts created in Manage Notice Board will appear here.', 'ستظهر هنا المنشورات النشطة التي يتم إنشاؤها من إدارة لوحة الإعلانات.'),
('pleaseLoginToLike', 'Please log in to like posts', 'يرجى تسجيل الدخول للإعجاب'),
('pleaseLoginToComment', 'Please log in to comment', 'يرجى تسجيل الدخول للتعليق'),
('failedToAddComment', 'Failed to add comment', 'فشل إضافة التعليق'),
('noCommentsYet', 'No comments yet', 'لا توجد تعليقات بعد'),
('writeAComment', 'Write a comment', 'اكتب تعليقاً'),
('postComment', 'Post', 'نشر'),
('likes', 'Likes', 'الإعجابات'),
('comments', 'Comments', 'التعليقات'),
('refresh', 'Refresh', 'تحديث'),
('tryAgain', 'Try again', 'حاول مرة أخرى'),
('alertsAndActivity', 'Alerts and Activity', 'التنبيهات والنشاط'),
('noData', 'No data', 'لا توجد بيانات'),
('summaryAnalyticsContentComingSoon', 'Summary Analytics Content Coming Soon', 'محتوى التحليلات الملخصة قادم قريباً'),
('customReportsContentComingSoon', 'Custom Reports Content Coming Soon', 'محتوى التقارير المخصصة قادم قريباً'),
('createNewTeam', 'Create New Team', 'إنشاء فريق جديد'),
('editUserTeam', 'Edit User Team', 'تعديل فريق المستخدمين'),
('createUserTeam', 'Create User Team', 'إنشاء فريق مستخدمين'),
('teamName', 'Team Name', 'اسم الفريق'),
('teamNamePlaceholder', 'e.g., East Zonal Team, Store Ops Leads', 'مثال: فريق المنطقة الشرقية، قادة عمليات المتجر'),
('updateTeam', 'Update Team', 'تحديث الفريق'),
('createTeam', 'Create Team', 'إنشاء الفريق'),
('members', 'Members', 'الأعضاء'),
('member', 'member', 'عضو'),
('membersPlural', 'members', 'أعضاء'),
('noUserTeamsAvailable', 'No user teams available', 'لا توجد فرق مستخدمين'),
('searchByName', 'Search by name', 'البحث بالاسم'),
('filterByEmail', 'Filter by email', 'تصفية حسب البريد الإلكتروني'),
('userHierarchy', 'User Hierarchy', 'التسلسل الهرمي للمستخدمين'),
('expandAll', 'Expand All', 'توسيع الكل'),
('collapseAll', 'Collapse All', 'طي الكل'),
('selectHierarchyUser', 'Select a user from the hierarchy to view details', 'اختر مستخدماً من التسلسل الهرمي لعرض التفاصيل'),
('storesUnderCoverage', 'Stores under coverage', 'المتاجر ضمن نطاق التغطية'),
('userDetails', 'User Details', 'تفاصيل المستخدم'),
('advanceMapping', 'Advance Mapping', 'التعيين المتقدم'),
('advanceMappingTitle', 'Advance Mapping - Report Access', 'التعيين المتقدم - صلاحية التقارير'),
('advanceMappingDescription', 'Give users report access to additional stores beyond their default mapped stores.', 'منح المستخدمين صلاحية الوصول إلى تقارير متاجر إضافية بخلاف المتجر الافتراضي المعين لهم.'),
('addAdvanceMapping', 'Add Advance Mapping', 'إضافة تعيين متقدم'),
('advanceMappingEmpty', 'No advance mapped users yet. Click "Add Advance Mapping" to assign report access.', 'لا يوجد مستخدمون معينون بعد. انقر "إضافة تعيين متقدم" لتعيين صلاحية التقارير.'),
('advanceMappingNoStoresHint', 'Create additional stores in Organization Management before assigning advance report access.', 'أنشئ متاجر إضافية في إدارة المنظمة قبل تعيين صلاحيات التقارير المتقدمة.'),
('advanceMappingStores', 'Stores for Report Access', 'المتاجر لصلاحية التقارير'),
('advanceMappingNoStoresAvailable', 'No stores available', 'لا توجد متاجر متاحة'),
('advanceMappingSelectUserFirst', 'Select a user first to enable store selection.', 'اختر مستخدماً أولاً لتمكين اختيار المتاجر.'),
('advanceMappingNoEligibleStores', 'This user already has access only to their default store. Add more stores in Organization Management to create advance mappings.', 'لدى هذا المستخدم صلاحية متجره الافتراضي فقط. أضف المزيد من المتاجر في إدارة المنظمة لإنشاء تعيينات متقدمة.'),
('advanceMappingDefaultStore', 'default store', 'المتجر الافتراضي'),
('advanceMappingCreated', 'Advance mapping created', 'تم إنشاء التعيين المتقدم'),
('advanceMappingUpdated', 'Advance mapping updated', 'تم تحديث التعيين المتقدم'),
('advanceMappingDeleted', 'Advance mapping removed', 'تمت إزالة التعيين المتقدم'),
('advanceMappingSaveFailed', 'Failed to save advance mapping', 'فشل حفظ التعيين المتقدم'),
('advanceMappingDeleteFailed', 'Failed to remove advance mapping', 'فشلت إزالة التعيين المتقدم'),
('advanceMappingSelectUser', 'Select a user first', 'اختر مستخدماً أولاً'),
('advanceMappingSelectStore', 'Select at least one additional store for report access', 'اختر متجراً إضافياً واحداً على الأقل لصلاحية التقارير'),
('advanceMappingDeleteConfirm', 'Remove all advance mapping for this user?', 'إزالة كل التعيين المتقدم لهذا المستخدم؟'),
('advanceMappingEditTitle', 'Edit Report Access', 'تعديل صلاحية التقارير'),
('advanceMappingAddTitle', 'Add Advance Mapping', 'إضافة تعيين متقدم'),
('advanceMappingAddDescription', 'Select a user and choose additional stores for report access.', 'اختر مستخدماً وحدد المتاجر الإضافية لصلاحية التقارير.'),
('advanceMappingEditDescription', 'Update additional stores this user can access for reporting:', 'حدّث المتاجر الإضافية التي يمكن لهذا المستخدم الوصول إليها للتقارير:'),
('advanceMappingAdditionalStores', 'Additional stores', 'المتاجر الإضافية'),
('advanceMappingNone', 'None', 'لا يوجد'),
('advanceMappingDefaultStoreHint', 'Default store cannot be added as an additional mapping.', 'لا يمكن إضافة المتجر الافتراضي كتعيين إضافي.'),
('advanceMappingCreate', 'Create', 'إنشاء'),
('advanceMappingUpdate', 'Update Mapping', 'تحديث التعيين'),
('region', 'Region', 'المنطقة'),
('district', 'District', 'الحي'),
('city', 'City', 'المدينة'),
('selectRegion', 'Select region', 'اختر المنطقة'),
('selectCity', 'Select city', 'اختر المدينة'),
('selectDistrict', 'Select district', 'اختر الحي'),
('selectRegionFirst', 'Select region first', 'اختر المنطقة أولاً'),
('selectCityFirst', 'Select city first', 'اختر المدينة أولاً'),
('loadingRegions', 'Loading regions...', 'جاري تحميل المناطق...'),
('loadingCities', 'Loading cities...', 'جاري تحميل المدن...'),
('loadingDistricts', 'Loading districts...', 'جاري تحميل الأحياء...'),
('country', 'Country', 'الدولة'),
('state', 'State', 'الولاية / المنطقة'),
('countryStateCity', 'Country / State / City', 'الدولة / الولاية / المدينة'),
('countryStateCityHint', 'Select from the generic location hierarchy', 'اختر من التسلسل الهرمي العام للمواقع'),
('selectCountry', 'Select country', 'اختر الدولة'),
('selectState', 'Select state', 'اختر الولاية'),
('selectCountryFirst', 'Select country first', 'اختر الدولة أولاً'),
('selectStateFirst', 'Select state first', 'اختر الولاية أولاً'),
('loading', 'Loading...', 'جاري التحميل...'),
('reportingAndInsights', 'Reporting & Insights', 'التقارير والرؤى'),
('reportingAndInsightsIntro', 'Access reports, dashboards, and analytics across your organization.', 'الوصول إلى التقارير ولوحات المعلومات والتحليلات عبر مؤسستك.'),
('customDashboards', 'Custom Dashboards', 'لوحات المعلومات المخصصة'),
('customDashboardsDesc', 'Build tailored Process, Ticket & Action Point dashboards with bar, line, pie, and table charts, filters, sharing, and templates.', 'أنشئ لوحات مخصصة للعمليات والتذاكر ونقاط العمل مع مخططات شريطية وخطية ودائرية وجداول وفلاتر ومشاركة وقوالب.'),
('customDashboardsRoles', 'Admin, Manager', 'المسؤول، المدير'),
('dashboardTemplateLibrary', 'Dashboard Template Library', 'مكتبة قوالب لوحات المعلومات'),
('dashboardTemplateLibraryDesc', 'Start quickly with pre-built dashboard layouts for process, ticket, and action point reporting.', 'ابدأ بسرعة باستخدام تخطيطات جاهزة لتقارير العمليات والتذاكر ونقاط العمل.'),
('biDashboard', 'Custom Dashboards', 'لوحات المعلومات المخصصة'),
('useTemplate', 'Use Template', 'استخدام القالب'),
('viewDashboard', 'View Dashboard', 'عرض لوحة المعلومات'),
('createFromTemplate', 'Create from Template', 'إنشاء من قالب'),
('templateNameOptional', 'Dashboard name (optional)', 'اسم لوحة المعلومات (اختياري)'),
('featureReports', 'Feature Reports', 'تقارير الميزات'),
('featureReportsDesc', 'Detailed reports across modules and workflows.', 'تقارير تفصيلية عبر الوحدات وسير العمل.'),
('processReports', 'Process Reports', 'تقارير العمليات'),
('processReportsDesc', 'Analyze process completion, compliance, and multi-level performance.', 'تحليل إكمال العمليات والامتثال والأداء متعدد المستويات.'),
('actionPointsReports', 'Action Points Reports', 'تقارير نقاط العمل'),
('actionPointsReportsDesc', 'Track issue resolution, overdue items, and assignee performance.', 'تتبع حل المشكلات والعناصر المتأخرة وأداء المكلفين.'),
('ticketReports', 'Ticket Reports', 'تقارير التذاكر'),
('ticketReportsDesc', 'Track ticket status, resolution time, categories, and vendor/assignee performance.', 'تتبع حالة التذاكر ووقت الحل والفئات وأداء الموردين والمكلفين.'),
('assetReports', 'Asset Reports', 'تقارير الأصول'),
('assetReportsDesc', 'Track asset status, expiry, renewal, utilization, and history.', 'تتبع حالة الأصول والانتهاء والتجديد والاستخدام والسجل.'),
('learningReports', 'Learning Reports', 'تقارير التعلم'),
('learningReportsDesc', 'Monitor course completion, learner progress, assessments, and training compliance.', 'مراقبة إكمال الدورات وتقدم المتعلمين والتقييمات والامتثال للتدريب.'),
('assessmentReports', 'Assessment Reports', 'تقارير التقييمات'),
('assessmentReportsDesc', 'Assessment results and completion reports.', 'نتائج التقييمات وتقارير الإكمال.'),
('storeHealthCompliance', 'Store Health & Compliance', 'صحة المتجر والامتثال'),
('storeHealthComplianceDesc', 'Executive view of store compliance and health metrics.', 'عرض تنفيذي لمقاييس امتثال وصحة المتجر.'),
('storeReportDesc', 'Store-level process and audit submissions', 'إرسالات العمليات والتدقيق على مستوى المتجر'),
('organizationReportDesc', 'Organization-wide process and audit submissions', 'إرسالات العمليات والتدقيق على مستوى المنظمة'),
('visualReportDesc', 'Visual analytics and insights', 'تحليلات ورؤى مرئية'),
('totalSubmissions', 'Total Submissions', 'إجمالي الإرسالات'),
('completionRate', 'Completion Rate', 'معدل الإكمال'),
('workflowTypeDistribution', 'Workflow Type Distribution', 'توزيع نوع سير العمل'),
('statusDistribution', 'Status Distribution', 'توزيع الحالة'),
('submissionsByStore', 'Submissions by Store', 'الإرسالات حسب المتجر'),
('submissionsByDate', 'Submissions by Date', 'الإرسالات حسب التاريخ'),
('noDataAvailable', 'No data available', 'لا توجد بيانات متاحة'),
('noPendingTasksInQueue', 'No pending tasks for this day', 'لا توجد مهام معلقة لهذا اليوم'),
('featurePermissions', 'Feature Permissions', 'صلاحيات الميزات'),
('correction', 'Correction', 'تصحيح'),
('rejected', 'Rejected', 'مرفوض'),
('selectStore', 'Select store...', 'اختر المتجر...'),
('searchSubmissions', 'Search submissions...', 'بحث في الإرسالات...'),
('thisWeek', 'This Week', 'هذا الأسبوع'),
('thisMonth', 'This Month', 'هذا الشهر'),
('allStatus', 'All Status', 'كل الحالات'),
('passed', 'Passed', 'ناجح'),
('failed', 'Failed', 'راسب'),
('raiseActionPoint', 'Raise Action Point', 'رفع نقطة عمل'),
('view', 'View', 'عرض'),
('audits', 'Audits', 'عمليات التدقيق'),
('searchAudit', 'Search Audit', 'بحث التدقيق'),
('reset', 'Reset', 'إعادة تعيين'),
('locationOptionalHint', 'Optional — you can add region, city, and district later.', 'اختياري — يمكنك إضافة المنطقة والمدينة والحي لاحقاً.'),
('locationDataUnavailable', 'Location list is unavailable. You can still create the entity without it.', 'قائمة المواقع غير متاحة. يمكنك إنشاء الكيان بدونها.'),
('entityCreatedSuccessfully', 'Entity created successfully', 'تم إنشاء الكيان بنجاح'),
('entityCreateFailed', 'Failed to create entity', 'فشل إنشاء الكيان'),
('entityUpdateFailed', 'Failed to update entity', 'فشل تحديث الكيان'),
('streetName', 'Street name', 'اسم الشارع'),
('address', 'Address', 'العنوان'),
('myProfile', 'My Profile', 'ملفي الشخصي'),
('changePassword', 'Change Password', 'تغيير كلمة المرور'),
('notifications', 'Notifications', 'الإشعارات'),
('profileSettings', 'Profile Settings', 'إعدادات الملف الشخصي'),
('manageYourPersonalSettings', 'Manage your personal settings', 'إدارة إعداداتك الشخصية'),
('personalInformation', 'Personal Information', 'المعلومات الشخصية'),
('accountInformation', 'Account Information', 'معلومات الحساب'),
('fullName', 'Full Name', 'الاسم الكامل'),
('employeeId', 'Employee ID', 'معرف الموظف'),
('reportingManager', 'Reporting Manager', 'المدير المباشر'),
('accountStatus', 'Account Status', 'حالة الحساب'),
('joinedDate', 'Joined Date', 'تاريخ الانضمام'),
('lastLogin', 'Last Login', 'آخر تسجيل دخول'),
('saveChanges', 'Save Changes', 'حفظ التغييرات'),
('savePreferences', 'Save Preferences', 'حفظ التفضيلات'),
('profileSavedSuccessfully', 'Profile saved successfully', 'تم حفظ الملف الشخصي بنجاح'),
('passwordChangedSuccessfully', 'Password changed successfully', 'تم تغيير كلمة المرور بنجاح'),
('fillAllPasswordFields', 'Please fill all password fields', 'يرجى ملء جميع حقول كلمة المرور'),
('passwordsDoNotMatch', 'Passwords do not match', 'كلمتا المرور غير متطابقتين'),
('passwordPolicyHint', 'Password must be at least 8 characters and include 1 lowercase letter, 1 number, and 1 special character', 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتتضمن حرفًا صغيرًا ورقمًا ورمزًا خاصًا'),
('changePasswordDescription', 'Update your password to keep your account secure', 'قم بتحديث كلمة المرور للحفاظ على أمان حسابك'),
('enterCurrentPassword', 'Enter current password', 'أدخل كلمة المرور الحالية'),
('enterNewPassword', 'Enter new password', 'أدخل كلمة المرور الجديدة'),
('pleaseLoginToChangePassword', 'You must be logged in to change your password', 'يجب تسجيل الدخول لتغيير كلمة المرور'),
('failedToChangePassword', 'Failed to change password', 'فشل تغيير كلمة المرور'),
('currentPasswordIncorrect', 'Current password is incorrect', 'كلمة المرور الحالية غير صحيحة'),
('newPasswordMustDiffer', 'New password must be different from the current password', 'يجب أن تختلف كلمة المرور الجديدة عن الحالية'),
('notificationSettingsSaved', 'Notification settings saved', 'تم حفظ إعدادات الإشعارات'),
('currentPassword', 'Current Password', 'كلمة المرور الحالية'),
('newPassword', 'New Password', 'كلمة المرور الجديدة'),
('confirmNewPassword', 'Confirm New Password', 'تأكيد كلمة المرور الجديدة'),
('updatePassword', 'Update Password', 'تحديث كلمة المرور'),
('notificationPreferences', 'Notification Preferences', 'تفضيلات الإشعارات'),
('notificationPreferencesSummary', 'Your notification preferences', 'تفضيلات الإشعارات الخاصة بك'),
('loginToManageNotifications', 'Sign in to manage your notification preferences.', 'سجّل الدخول لإدارة تفضيلات الإشعارات.'),
('unsavedNotificationChanges', 'You have unsaved notification preference changes.', 'لديك تغييرات غير محفوظة في تفضيلات الإشعارات.'),
('unsavedChanges', 'Unsaved', 'غير محفوظ'),
('enabled', 'Enabled', 'مفعّل'),
('on', 'On', 'تشغيل'),
('emailNotifications', 'Email Notifications', 'إشعارات البريد الإلكتروني'),
('pushNotifications', 'Push Notifications', 'الإشعارات الفورية'),
('taskReminders', 'Task Reminders', 'تذكيرات المهام'),
('deadlineAlerts', 'Deadline Alerts', 'تنبيهات المواعيد النهائية'),
('weeklyDigest', 'Weekly Digest', 'الملخص الأسبوعي'),
('mentions', 'Mentions', 'الإشارات'),
('learningNotifications', 'Learning Notifications', 'إشعارات التعلم'),
('learningNotificationsHint', 'Control alerts for course assignments and certificate issuance when you complete learning.', 'تحكم في تنبيهات تعيينات الدورات وإصدار الشهادات عند إكمال التعلم.'),
('learningAssignments', 'Course & assessment assignments', 'تعيينات الدورات والتقييمات'),
('certificateIssued', 'Certificate issuance', 'إصدار الشهادة'),
('courseCompletionReminders', 'Course completion reminders', 'تذكيرات إكمال الدورة'),
('courseCompletionRemindersHint', 'Remind you to finish assigned courses before the due date or when overdue.', 'تذكيرك بإنهاء الدورات المعينة قبل موعد الاستحقاق أو عند التأخير.'),
('noNotificationsYet', 'No notifications yet', 'لا توجد إشعارات بعد'),
('receiveNotificationsViaEmail', 'Receive notifications via email', 'تلقي الإشعارات عبر البريد الإلكتروني'),
('receivePushNotifications', 'Receive push notifications on your device', 'تلقي إشعارات فورية على جهازك'),
('remindedAboutUpcomingTasks', 'Get reminded about upcoming tasks', 'الحصول على تذكير بالمهام القادمة'),
('alertsWhenDeadlinesApproaching', 'Alerts when deadlines are approaching', 'تنبيهات عند اقتراب المواعيد النهائية'),
('weeklyDigestDesc', 'Receive a weekly summary of activities', 'تلقي ملخص أسبوعي للأنشطة'),
('notifiedWhenMentioned', 'Get notified when you''re mentioned', 'الحصول على إشعار عند الإشارة إليك'),
('rememberMe', 'Remember me', 'تذكرني'),
('forgotPassword', 'Forgot password?', 'نسيت كلمة المرور؟'),
('welcomeBack', 'Welcome back', 'مرحباً بعودتك'),
('pleaseEnterDetailsSignIn', 'Please enter your details to sign in', 'يرجى إدخال بياناتك لتسجيل الدخول'),
('signIn', 'Sign in', 'تسجيل الدخول'),
('signingIn', 'Signing in...', 'جاري تسجيل الدخول...'),
('invalidEmailOrPassword', 'Invalid email or password', 'البريد الإلكتروني أو كلمة المرور غير صحيحة'),
('failedToConnectToServer', 'Failed to connect to server', 'فشل الاتصال بالخادم'),
('notificationSettings', 'Notification Settings', 'إعدادات الإشعارات'),
('manageNotificationPreferences', 'Manage notification preferences', 'إدارة تفضيلات الإشعارات'),
('dailyDigest', 'Daily Digest', 'الملخص اليومي'),
('urgentOnly', 'Urgent only', 'العاجل فقط'),
('emailFrequency', 'Email frequency', 'تكرار البريد الإلكتروني'),
('instantAlerts', 'Instant', 'فوري'),
('emailFrequencyHint', 'Daily and weekly digests batch non-urgent emails. Urgent-only sends high-priority alerts immediately.', 'تجمّع الملخصات اليومية والأسبوعية رسائل البريد غير العاجلة. وضع العاجل فقط يرسل التنبيهات عالية الأولوية فوراً.'),
('enableEmailNotifications', 'Enable email notifications', 'تفعيل إشعارات البريد الإلكتروني'),
('emailDeliveryAddress', 'Delivery address', 'عنوان التسليم'),
('noEmailOnProfile', 'Add email in your profile', 'أضف البريد الإلكتروني في ملفك الشخصي'),
('currentEmailFrequency', 'Current', 'الحالي'),
('emailNotificationsDisabled', 'Email notifications are turned off.', 'إشعارات البريد الإلكتروني متوقفة.'),
('emailNotificationTypes', 'Email notification types', 'أنواع إشعارات البريد'),
('emailNotificationTypesHint', 'Choose which updates are sent to your email. In-app settings are configured separately.', 'اختر التحديثات التي تُرسل إلى بريدك. إعدادات داخل التطبيق منفصلة أدناه.'),
('inAppNotificationTypes', 'In-app notification types', 'أنواع الإشعارات داخل التطبيق'),
('inAppNotificationTypesHint', 'Turn off specific in-app alerts while keeping others enabled.', 'أوقف تنبيهاً محدداً داخل التطبيق مع إبقاء الأنواع الأخرى مفعّلة.'),
('inAppNotificationsDisabled', 'In-app notifications are turned off. Enable them above to configure types.', 'إشعارات داخل التطبيق متوقفة. فعّلها أعلاه لتكوين الأنواع.'),
('pushNotificationTypes', 'Push notification types', 'أنواع إشعارات الدفع'),
('pushNotificationTypesHint', 'Choose which updates trigger push alerts on your devices.', 'اختر التحديثات التي تُرسل تنبيهات دفع إلى أجهزتك.'),
('desktopAlerts', 'Desktop alerts', 'تنبيهات سطح المكتب'),
('mobileAlerts', 'Mobile alerts', 'تنبيهات الجوال'),
('smsNotifications', 'SMS Notifications', 'إشعارات الرسائل النصية'),
('urgentMessagesOnly', 'Urgent messages only', 'الرسائل العاجلة فقط'),
('inAppNotifications', 'In-App Notifications', 'إشعارات داخل التطبيق'),
('inAppNotificationsHint', 'Show alerts inside the application', 'عرض التنبيهات داخل التطبيق'),
('soundAlerts', 'Sound alerts', 'تنبيهات صوتية'),
('notificationTypes', 'Notification types', 'أنواع الإشعارات'),
('saveSettings', 'Save settings', 'حفظ الإعدادات'),
('saveNotificationSettings', 'Save notification settings', 'حفظ إعدادات الإشعارات'),
('emailConfig', 'Email Config', 'إعداد البريد الإلكتروني'),
('emailConfigSaved', 'Email configuration saved', 'تم حفظ إعداد البريد الإلكتروني'),
('cancelChanges', 'Cancel changes', 'إلغاء التغييرات'),
('off', 'Off', 'إيقاف'),
('edit', 'Edit', 'تعديل'),
('delete', 'Delete', 'حذف'),
('cancel', 'Cancel', 'إلغاء'),
('save', 'Save', 'حفظ'),
('action', 'Action', 'إجراء'),
('users', 'Users', 'المستخدمون'),
('notAvailable', 'N/A', 'غير متاح'),
('unknownStore', 'Unknown store', 'متجر غير معروف'),
('unknownUser', 'Unknown user', 'مستخدم غير معروف'),
('hybridAssignee', 'Hybrid Assignee', 'المكلف الهجين'),
('hybridAssigneeTitle', 'Hybrid Assignee Profile', 'ملف المكلف الهجين'),
('hybridAssigneeDescription', 'Manage stores, profiles, and user assignments for workflow automation.', 'إدارة المتاجر والملفات وتعيينات المستخدمين لأتمتة سير العمل.'),
('hybridStores', 'Stores', 'المتاجر'),
('hybridProfiles', 'Profiles', 'الملفات'),
('hybridTotalAssignments', 'Total Assignments', 'إجمالي التعيينات'),
('hybridActive', 'Active', 'نشط'),
('hybridConfigured', 'Configured', 'مُعد'),
('hybridUsers', 'Users', 'المستخدمون'),
('hybridCreate', 'Create', 'إنشاء'),
('hybridAddStores', 'Add Store(s)', 'إضافة متجر (متاجر)'),
('hybridAddProfile', 'Add Profile', 'إضافة ملف'),
('hybridStoreName', 'Store Name', 'اسم المتجر'),
('hybridSearch', 'Search', 'بحث'),
('hybridPublished', 'Published', 'منشور'),
('hybridDraft', 'Draft', 'مسودة'),
('hybridAssignUsers', 'Assign users', 'تعيين مستخدمين'),
('hybridAssignUsersTitle', 'Assign Users', 'تعيين المستخدمين'),
('hybridAddProfileTitle', 'Add Profile', 'إضافة ملف'),
('hybridAddStoresTitle', 'Add Store(s)', 'إضافة متجر (متاجر)'),
('hybridProfileName', 'Profile Name', 'اسم الملف'),
('hybridProfileNamePlaceholder', 'e.g., Operations Team', 'مثال: فريق العمليات'),
('hybridAddSelected', 'Add Selected', 'إضافة المحدد'),
('hybridAllStoresAdded', 'All stores are already added.', 'تمت إضافة جميع المتاجر بالفعل.'),
('hybridNoUsersAvailable', 'No users available', 'لا يوجد مستخدمون متاحون'),
('hybridSelectUsersHint', 'Select users for this store and profile.', 'اختر المستخدمين لهذا المتجر والملف.'),
('hybridAddProfileHint', 'Create a hybrid assignee profile column (max {max} profiles).', 'إنشاء عمود ملف مكلف هجين (الحد الأقصى {max} ملفات).'),
('hybridRenameProfileHint', 'Rename this hybrid assignee profile.', 'إعادة تسمية ملف المكلف الهجين هذا.'),
('hybridAddStoresHint', 'Select stores to include in the hybrid assignee matrix.', 'اختر المتاجر لتضمينها في مصفوفة المكلف الهجين.'),
('hybridAddProfileToAssign', 'Add a profile column to assign users', 'أضف عمود ملف لتعيين المستخدمين'),
('hybridAddProfileToAssignRow', 'Add a profile to assign users', 'أضف ملفاً لتعيين المستخدمين'),
('hybridAddStoresToBuild', 'Add store(s) to build the assignment matrix', 'أضف متجراً (متاجر) لبناء مصفوفة التعيين'),
('hybridNoStoresMatchSearch', 'No stores match your search', 'لا توجد متاجر تطابق بحثك'),
('hybridLoadFailed', 'Failed to load hybrid assignee data', 'فشل تحميل بيانات المكلف الهجين'),
('hybridProfileNameRequired', 'Profile name is required', 'اسم الملف مطلوب'),
('hybridProfileCreated', 'Profile created', 'تم إنشاء الملف'),
('hybridProfileCreateFailed', 'Failed to create profile', 'فشل إنشاء الملف'),
('hybridSelectStore', 'Select at least one store', 'اختر متجراً واحداً على الأقل'),
('hybridStoresAdded', 'Stores added', 'تمت إضافة المتاجر'),
('hybridStoresAddFailed', 'Failed to add stores', 'فشلت إضافة المتاجر'),
('hybridRemoveStoreConfirm', 'Remove store "{name}" from hybrid assignee?', 'إزالة المتجر "{name}" من المكلف الهجين؟'),
('hybridStoreRemoved', 'Store removed', 'تمت إزالة المتجر'),
('hybridStoreRemoveFailed', 'Failed to remove store', 'فشلت إزالة المتجر'),
('hybridProfileUpdated', 'Profile updated', 'تم تحديث الملف'),
('hybridProfileUpdateFailed', 'Failed to update profile', 'فشل تحديث الملف'),
('hybridProfilePublished', 'Profile published', 'تم نشر الملف'),
('hybridProfilePublishFailed', 'Failed to publish profile', 'فشل نشر الملف'),
('hybridDeleteProfileConfirm', 'Delete profile "{name}"?', 'حذف الملف "{name}"؟'),
('hybridProfileDeleted', 'Profile deleted', 'تم حذف الملف'),
('hybridProfileDeleteFailed', 'Failed to delete profile', 'فشل حذف الملف'),
('hybridAssignmentsSaved', 'Assignments saved', 'تم حفظ التعيينات'),
('hybridAssignmentsSaveFailed', 'Failed to save assignments', 'فشل حفظ التعيينات'),
('publish', 'Publish', 'نشر'),
('attendanceTracking', 'Attendance Tracking', 'تتبع الحضور'),
('trackAndManageEmployeeAttendance', 'Track and manage employee attendance automatically', 'تتبع وإدارة حضور الموظفين تلقائياً'),
('autoAttendance', 'Automatic Attendance', 'الحضور التلقائي'),
('autoAttendanceDescription', 'Punch-in is recorded when users log in. Punch-out is recorded when they log out.', 'يُسجَّل الدخول عند تسجيل الدخول ويُسجَّل الخروج عند تسجيل الخروج.'),
('noActiveSession', 'No active session', 'لا توجد جلسة نشطة'),
('activeSession', 'Checked in', 'تم تسجيل الدخول'),
('sessionCompleted', 'Completed today', 'اكتمل اليوم'),
('myAttendanceToday', 'My Attendance Today', 'حضوري اليوم'),
('punchIn', 'Punch In', 'تسجيل الدخول'),
('punchOut', 'Punch Out', 'تسجيل الخروج'),
('notYet', 'Not yet', 'لم يُسجَّل بعد'),
('noRecord', 'No record', 'لا يوجد سجل'),
('timeSpent', 'Time Spent', 'الوقت المقضى'),
('autoCheckInOn', 'Auto check-in ON', 'تسجيل الدخول التلقائي مفعّل'),
('autoCheckInOff', 'Auto check-in OFF', 'تسجيل الدخول التلقائي متوقف'),
('autoCheckOutOn', 'Auto check-out ON', 'تسجيل الخروج التلقائي مفعّل'),
('autoCheckOutOff', 'Auto check-out OFF', 'تسجيل الخروج التلقائي متوقف'),
('kpiOverview', 'KPI Overview', 'نظرة عامة على المؤشرات'),
('totalRecords', 'Total Records', 'إجمالي السجلات'),
('totalAttendanceEntriesAvailable', 'Attendance entries in selected range', 'سجلات الحضور في النطاق المحدد'),
('daysCovered', 'Days Covered', 'الأيام المغطاة'),
('totalDistinctDaysIncluded', 'Days included in filter', 'الأيام ضمن الفلتر'),
('employees', 'Employees', 'الموظفون'),
('uniqueEmployeesWithAtLeastOnePunch', 'Unique employees with punches', 'موظفون فريدون لديهم بصمات'),
('stores', 'Stores', 'المتاجر'),
('uniqueStoresWithAttendanceActivity', 'Stores with activity', 'متاجر بها نشاط حضور'),
('expectedWorkHrs', 'Expected Hours', 'الساعات المتوقعة'),
('totalScheduledHoursBasedOnWorkingHours', 'Scheduled hours in range', 'الساعات المجدولة في النطاق'),
('actualWorkHrs', 'Actual Hours', 'الساعات الفعلية'),
('hoursCalculatedFromPunchInOut', 'From punch in/out times', 'من أوقات الدخول والخروج'),
('utilization', 'Utilization', 'نسبة الاستخدام'),
('actualHoursVsExpectedHours', 'Actual vs expected', 'الفعلي مقابل المتوقع'),
('overtime', 'Overtime', 'وقت إضافي'),
('hoursWorkedBeyondExpected', 'Hours beyond expected', 'ساعات فوق المتوقع'),
('undertime', 'Undertime', 'نقص الوقت'),
('hoursShortOfExpectedTime', 'Hours below expected', 'ساعات أقل من المتوقع'),
('notPunchedOut', 'Not Punched Out', 'لم يسجّل الخروج'),
('entriesWithoutValidPunchOut', 'Missing punch-out', 'سجلات بدون خروج'),
('attendanceRecords', 'Attendance Records', 'سجلات الحضور'),
('loadingAttendanceRecords', 'Loading attendance records…', 'جاري تحميل سجلات الحضور…'),
('searchByUserNameOrId', 'Search by name, ID, or email', 'بحث بالاسم أو المعرف أو البريد'),
('searchAttendanceRecords', 'Search attendance records', 'بحث في سجلات الحضور'),
('filterByDateRange', 'Filter by date range', 'تصفية حسب نطاق التاريخ'),
('apply', 'Apply', 'تطبيق'),
('configureAttendance', 'Configure Attendance', 'إعداد الحضور'),
('toggleAttendanceOnOff', 'Enable or disable attendance tracking', 'تفعيل أو إيقاف تتبع الحضور'),
('geolocation', 'Geolocation', 'الموقع الجغرافي'),
('enforcesGpsBasedCheckInOut', 'Require GPS for check-in/out', 'يتطلب GPS للدخول/الخروج'),
('checkInImage', 'Check-in Image', 'صورة تسجيل الدخول'),
('requiresUserToTakeSelfie', 'Require selfie on check-in', 'يتطلب selfie عند الدخول'),
('checkOutImage', 'Check-out Image', 'صورة تسجيل الخروج'),
('requiresSelfieOnCheckOut', 'Require selfie on check-out', 'يتطلب selfie عند الخروج'),
('autoCheckInOnLogin', 'Automatic check-in on login', 'تسجيل دخول تلقائي عند Login'),
('autoCheckInOnLoginDesc', 'Record punch-in when a user signs in', 'تسجيل الدخول عند تسجيل المستخدم'),
('autoCheckOutOnLogout', 'Automatic check-out on logout', 'تسجيل خروج تلقائي عند Logout'),
('autoCheckOutOnLogoutDesc', 'Record punch-out when a user signs out', 'تسجيل الخروج عند خروج المستخدم'),
('operatingHours', 'Operating Hours', 'ساعات العمل'),
('startTime', 'Start Time', 'وقت البداية'),
('endTime', 'End Time', 'وقت النهاية'),
('defineWhenStoreWorkdayStarts', 'When the workday starts', 'بداية يوم العمل'),
('defineWhenStoreWorkdayEnds', 'When the workday ends', 'نهاية يوم العمل'),
('dailyWorkingHours', 'Daily Working Hours', 'ساعات العمل اليومية'),
('setHowManyHoursCountAsCompleteWorkday', 'Hours counted as a full workday', 'ساعات اليوم الكامل'),
('calculateTimeDifferenceOvertime', 'Calculate overtime / undertime', 'حساب الوقت الإضافي / النقص'),
('automaticallyCalculateOverUnderTime', 'Auto-calculate time differences', 'حساب الفروقات تلقائياً'),
('saveConfiguration', 'Save Configuration', 'حفظ الإعدادات'),
('publishAttendanceSettings', 'Publish Attendance Settings', 'نشر إعدادات الحضور'),
('assignAttendancePolicies', 'Assign attendance policies to stores or users', 'تعيين سياسات الحضور للمتاجر أو المستخدمين'),
('byStore', 'By Store', 'حسب المتجر'),
('byUser', 'By User', 'حسب المستخدم'),
('assigneeProfile', 'Assignee Profile', 'ملف المكلف'),
('quickAssign', 'Quick Assign', 'تعيين سريع'),
('searchStores', 'Search stores', 'بحث في المتاجر'),
('searchUsers', 'Search users', 'بحث في المستخدمين'),
('noStoresSelected', 'No stores selected', 'لم يتم اختيار متاجر'),
('noUsersSelected', 'No users selected', 'لم يتم اختيار مستخدمين'),
('dragAndDropFileHere', 'Drag and drop file here', 'اسحب الملف وأفلته هنا'),
('chooseFile', 'Choose File', 'اختر ملفاً'),
('downloadAttendanceReport', 'Download attendance report', 'تنزيل تقرير الحضور'),
('report', 'Report', 'تقرير'),
('addStore', 'Add Store', 'إضافة متجر'),
('addUser', 'Add User', 'إضافة مستخدم'),
('selectStoresToAssignAttendancePolicies', 'Select stores for attendance policies', 'اختر المتاجر لسياسات الحضور'),
('selectUsersToAssignAttendancePolicies', 'Select users for attendance policies', 'اختر المستخدمين لسياسات الحضور'),
('loadingStores', 'Loading stores…', 'جاري تحميل المتاجر…'),
('loadingUsers', 'Loading users…', 'جاري تحميل المستخدمين…'),
('noStoresAvailable', 'No stores available', 'لا توجد متاجر'),
('noUsersAvailable', 'No users available', 'لا يوجد مستخدمون'),
('added', 'Added', 'مُضاف'),
('add', 'Add', 'إضافة'),
('close', 'Close', 'إغلاق'),
('addEntity', 'Add Entity', 'إضافة كيان'),
('present', 'Present', 'حاضر'),
('absent', 'Absent', 'غائب'),
('late', 'Late', 'متأخر'),
('checkedIn', 'Checked In', 'مسجّل الدخول'),
('onLeave', 'On Leave', 'في إجازة'),
('punchInImage', 'Punch In Image', 'صورة الدخول'),
('punchOutImage', 'Punch Out Image', 'صورة الخروج'),
('workingHours', 'Working Hours', 'ساعات العمل'),
('deviation', 'Deviation', 'الانحراف'),
('deviceInfo', 'Device Info', 'معلومات الجهاز'),
('status', 'Status', 'الحالة'),
('source', 'Source', 'المصدر'),
('filterStore', 'Filter by store', 'تصفية حسب المتجر'),
('filterUser', 'Filter by user', 'تصفية حسب المستخدم'),
('allStores', 'All stores', 'كل المتاجر'),
('allUsers', 'All users', 'كل المستخدمين')
ON CONFLICT (key) DO UPDATE SET en = EXCLUDED.en, ar = EXCLUDED.ar, updated_at = CURRENT_TIMESTAMP;
