import { createContext, useContext, useState, ReactNode } from "react";

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    home: "Home",
    tasks: "Tasks",
    actionPoints: "Action Points",
    issueTickets: "Issue Tickets",
    workflows: "Workflows",
    approvals: "Approvals",
    learning: "Learning",
    courses: "Courses",
    assessments: "Assessments",
    assets: "Assets",
    users: "Users",
    noticeboard: "Noticeboard",
    reports: "Reports",
    admin: "Admin",
    language: "Language",
    help: "Help",
    helpAndSupport: "Help & Support",
    creatorMode: "Creator Mode",
    goBack: "Go Back",
    notifications: "Notifications",
    settings: "Settings",
    profile: "Profile",
    // Dashboard
    dashboard: "Dashboard",
    standardReports: "Standard Reports",
    executiveDashboard: "Executive Dashboard",
    biDashboard: "BI Dashboard",
    myReport: "My Report",
    assignedTasks: "Assigned Tasks",
    reviewedTasks: "Reviewed Tasks",
    myTasks: "My Tasks",
    noTasksAvailableDateRange: "No Tasks available for this date range. Try selecting a different date range :)",
    storeReport: "Store Report",
    processReport: "Process Report",
    organizationReport: "Organization Report",
    visualReport: "Visual Report",
    expiredSubmissions: "Expired Submissions",
    teamReport: "Team Report",
    orgReport: "Org Report",
    assessmentReport: "Assessment Report",
    advanceSearch: "Advance Search",
    tagReport: "Tag Report",
    advanceReport: "Advance Report",
    organizations: "Organizations",
    tags: "Tags",
    platformSettings: "Platform Settings",
    securitySettings: "Security Settings",
    profileSettings: "Profile Settings",
    // Sidebar
    collapse: "Collapse",
    expand: "Expand",
    // Common actions
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    refresh: "Refresh",
    export: "Export",
    import: "Import",
    // Status
    active: "Active",
    inactive: "Inactive",
    published: "Published",
    draft: "Draft",
    archived: "Archived",
    deleted: "Deleted",
    // Messages
    noDataFound: "No data found",
    loading: "Loading...",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    // Dashboard page
    welcomeBack: "Welcome back",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    totalTasks: "Total Tasks",
    completedTasks: "Completed Tasks",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    viewAll: "View All",
    // Assets page
    assetsManagement: "Assets Management",
    trackAndManage: "Track and manage all store-level assets",
    configureTable: "Configure Table",
    exportCSV: "Export CSV",
    createEntry: "Create Entry",
    activeAssets: "Active Assets",
    deletedAssets: "Deleted Assets",
    assetId: "Asset ID",
    assetName: "Asset Name",
    customId: "Custom ID",
    store: "Store",
    assetStatus: "Status",
    assetExpiryDate: "Expiry Date",
    createdAt: "Created At",
    actions: "Actions",
    restore: "Restore",
    // Assessments page
    assessmentsQuizzes: "Assessments & Quizzes",
    createAndManage: "Create and manage assessments",
    newAssessment: "New Assessment",
    assessmentsList: "Assessments List",
    records: "records",
    passingScore: "Passing Score",
    duration: "Duration",
    attempts: "Attempts",
    passed: "Passed",
    avgScore: "Avg Score",
    createNewAssessment: "Create New Assessment",
    assessmentTitle: "Assessment Title",
    description: "Description",
    enterAssessmentTitle: "Enter assessment title",
    enterAssessmentDescription: "Enter assessment description",
    maxAttempts: "Max Attempts",
    allowRetake: "Allow Retake",
    assessmentExpiryDate: "Expiry Date",
    pickADate: "Pick a date",
    createAssessment: "Create Assessment",
    editAssessment: "Edit Assessment",
    modifyAssessmentDetails: "Modify assessment details",
    saveChanges: "Save Changes",
    // Categories and Courses
    categoriesAndCourses: "Categories and Courses",
    manageCategories: "Manage categories and courses",
    createCategory: "Create Category",
    categoryName: "Category Name",
    arabicName: "Arabic Name",
    enterCategoryName: "Enter category name",
    enterArabicName: "Enter Arabic name",
    createCourse: "Create Course",
    courseName: "Course Name",
    enterCourseName: "Enter course name",
    selectCategory: "Select Category",
    createCourseQuiz: "Create Course Quiz",
    quizTitle: "Quiz Title",
    quizDescription: "Quiz Description",
    timeLimit: "Time Limit (minutes)",
    passingScorePercent: "Passing Score (%)",
    assign: "Assign",
    publish: "Publish",
    // Attendance
    attendanceManagement: "Attendance Management",
    manageAttendance: "Manage employee attendance",
    configureAttendance: "Configure Attendance",
    attendanceStatus: "Status",
    geolocation: "Geolocation",
    checkInImage: "Check-in Image",
    checkOutImage: "Check-out Image",
    operatingHours: "Operating Hours",
    operatingHoursStart: "Operating Hours Start",
    operatingHoursEnd: "Operating Hours End",
    dailyWorkingHours: "Daily Working Hours",
    calculateOvertime: "Calculate Overtime",
    attendanceRecords: "Attendance Records",
    userName: "User Name",
    email: "Email",
    attendanceStore: "Store",
    date: "Date",
    checkInTime: "Check-in Time",
    checkOutTime: "Check-out Time",
    totalHours: "Total Hours",
    expectedHours: "Expected Hours",
    deviation: "Deviation",
    deviceInfo: "Device Info",
    addEntity: "Add Entity",
    assignBy: "Assign By",
    quickAssign: "Quick Assign",
    // Common UI elements
    yes: "Yes",
    no: "No",
    ok: "OK",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    select: "Select",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    apply: "Apply",
    reset: "Reset",
    clear: "Clear",
    confirm: "Confirm",
    deny: "Deny",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    completed: "Completed",
    inProgress: "In Progress",
    failed: "Failed",
    cancelled: "Cancelled",
  },
  ar: {
    // Common
    home: "الرئيسية",
    tasks: "المهام",
    actionPoints: "نقاط العمل",
    issueTickets: "تذاكر المشكلات",
    workflows: "سير العمل",
    approvals: "الموافقات",
    learning: "التعلم",
    courses: "الدورات",
    assessments: "التقييمات",
    assets: "الأصول",
    users: "المستخدمين",
    noticeboard: "لوحة الإعلانات",
    reports: "التقارير",
    admin: "الإدارة",
    language: "اللغة",
    help: "مساعدة",
    helpAndSupport: "مساعدة ودعم",
    creatorMode: "وضع المبدع",
    goBack: "العودة",
    notifications: "الإشعارات",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    // Dashboard
    dashboard: "لوحة التحكم",
    standardReports: "التقارير القياسية",
    executiveDashboard: "لوحة التنفيذية",
    biDashboard: "لوحة المعلومات التجارية",
    myReport: "تقريري",
    assignedTasks: "المهام المسندة",
    reviewedTasks: "المهام المراجعة",
    myTasks: "مهامي",
    noTasksAvailableDateRange: "لا توجد مهام متاحة لهذه الفترة الزمنية. حاول اختيار فترة زمنية مختلفة :)",
    storeReport: "تقرير المتجر",
    processReport: "تقرير العملية",
    organizationReport: "تقرير المنظمة",
    visualReport: "التقرير المرئي",
    expiredSubmissions: "العمليات المنتهية",
    teamReport: "تقرير الفريق",
    orgReport: "تقرير المنظمة",
    assessmentReport: "تقرير التقييم",
    advanceSearch: "بحث متقدم",
    tagReport: "تقرير العلامات",
    advanceReport: "تقرير متقدم",
    organizations: "المنظمات",
    tags: "العلامات",
    platformSettings: "إعدادات المنصة",
    securitySettings: "إعدادات الأمان",
    profileSettings: "إعدادات الملف الشخصي",
    // Sidebar
    collapse: "طي",
    expand: "توسيع",
    // Common actions
    create: "إنشاء",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    submit: "إرسال",
    search: "بحث",
    filter: "تصفية",
    refresh: "تحديث",
    export: "تصدير",
    import: "استيراد",
    // Status
    active: "نشط",
    inactive: "غير نشط",
    published: "منشور",
    draft: "مسودة",
    archived: "أرشيف",
    deleted: "محذوف",
    // Messages
    noDataFound: "لم يتم العثور على بيانات",
    loading: "جاري التحميل...",
    success: "نجاح",
    error: "خطأ",
    warning: "تحذير",
    info: "معلومات",
    // Dashboard page
    welcomeBack: "مرحباً بعودتك",
    totalUsers: "إجمالي المستخدمين",
    activeUsers: "المستخدمون النشطون",
    totalTasks: "إجمالي المهام",
    completedTasks: "المهام المكتملة",
    recentActivity: "النشاط الأخير",
    quickActions: "إجراءات سريعة",
    viewAll: "عرض الكل",
    // Assets page
    assetsManagement: "إدارة الأصول",
    trackAndManage: "تتبع وإدارة جميع أصول المتجر",
    configureTable: "تكوين الجدول",
    exportCSV: "تصدير CSV",
    createEntry: "إنشاء إدخال",
    activeAssets: "الأصول النشطة",
    deletedAssets: "الأصول المحذوفة",
    assetId: "معرف الأصل",
    assetName: "اسم الأصل",
    customId: "معرف مخصص",
    store: "المتجر",
    assetStatus: "الحالة",
    assetExpiryDate: "تاريخ الانتهاء",
    createdAt: "تم الإنشاء في",
    actions: "الإجراءات",
    restore: "استعادة",
    // Assessments page
    assessmentsQuizzes: "التقييمات والاختبارات",
    createAndManage: "إنشاء وإدارة التقييمات",
    newAssessment: "تقييم جديد",
    assessmentsList: "قائمة التقييمات",
    records: "سجلات",
    passingScore: "درجة النجاح",
    duration: "المدة",
    attempts: "المحاولات",
    passed: "نجح",
    avgScore: "متوسط الدرجة",
    createNewAssessment: "إنشاء تقييم جديد",
    assessmentTitle: "عنوان التقييم",
    description: "الوصف",
    enterAssessmentTitle: "أدخل عنوان التقييم",
    enterAssessmentDescription: "أدخل وصف التقييم",
    maxAttempts: "أقصى عدد من المحاولات",
    allowRetake: "السماح بإعادة المحاولة",
    assessmentExpiryDate: "تاريخ انتهاء التقييم",
    pickADate: "اختر تاريخ",
    createAssessment: "إنشاء التقييم",
    editAssessment: "تعديل التقييم",
    modifyAssessmentDetails: "تعديل تفاصيل التقييم",
    saveChanges: "حفظ التغييرات",
    // Categories and Courses
    categoriesAndCourses: "الفئات والدورات",
    manageCategories: "إدارة الفئات والدورات",
    createCategory: "إنشاء فئة",
    categoryName: "اسم الفئة",
    arabicName: "الاسم بالعربية",
    enterCategoryName: "أدخل اسم الفئة",
    enterArabicName: "أدخل الاسم بالعربية",
    createCourse: "إنشاء دورة",
    courseName: "اسم الدورة",
    enterCourseName: "أدخل اسم الدورة",
    selectCategory: "اختر الفئة",
    createCourseQuiz: "إنشاء اختبار الدورة",
    quizTitle: "عنوان الاختبار",
    quizDescription: "وصف الاختبار",
    timeLimit: "الحد الزمني (دقائق)",
    passingScorePercent: "درجة النجاح (%)",
    assign: "تعيين",
    publish: "نشر",
    // Attendance
    attendanceManagement: "إدارة الحضور",
    manageAttendance: "إدارة حضور الموظفين",
    configureAttendance: "تكوين الحضور",
    attendanceStatus: "الحالة",
    geolocation: "الموقع الجغرافي",
    checkInImage: "صورة تسجيل الدخول",
    checkOutImage: "صورة تسجيل الخروج",
    operatingHours: "ساعات العمل",
    operatingHoursStart: "بداية ساعات العمل",
    operatingHoursEnd: "نهاية ساعات العمل",
    dailyWorkingHours: "ساعات العمل اليومية",
    calculateOvertime: "حساب العمل الإضافي",
    attendanceRecords: "سجلات الحضور",
    userName: "اسم المستخدم",
    email: "البريد الإلكتروني",
    attendanceStore: "المتجر",
    date: "التاريخ",
    checkInTime: "وقت تسجيل الدخول",
    checkOutTime: "وقت تسجيل الخروج",
    totalHours: "إجمالي الساعات",
    expectedHours: "الساعات المتوقعة",
    deviation: "الانحراف",
    deviceInfo: "معلومات الجهاز",
    addEntity: "إضافة كيان",
    assignBy: "تعيين بواسطة",
    quickAssign: "تعيين سريع",
    // Common UI elements
    yes: "نعم",
    no: "لا",
    ok: "موافق",
    close: "إغلاق",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    finish: "إنهاء",
    select: "اختيار",
    selectAll: "اختيار الكل",
    deselectAll: "إلغاء اختيار الكل",
    apply: "تطبيق",
    reset: "إعادة تعيين",
    clear: "مسح",
    confirm: "تأكيد",
    deny: "رفض",
    approve: "موافقة",
    reject: "رفض",
    pending: "قيد الانتظار",
    completed: "مكتمل",
    inProgress: "قيد التنفيذ",
    failed: "فشل",
    cancelled: "ملغي",
    // Creator Mode
    creationAndConfigurations: "الإنشاء والتكوينات",
    processAndWorkflow: "العمليات وسير العمل",
    contentAndLearning: "المحتوى والتعلم",
    actionPointAndTicketConfig: "تكوين نقاط العمل والتذاكر",
    manageUsers: "إدارة المستخدمين",
    manageEntity: "إدارة الكيانات",
    manageTags: "إدارة العلامات",
    auditLogs: "سجلات التدقيق",
    noticeBoard: "لوحة الإعلانات",
    adminCenter: "مركز الإدارة",
    management: "الإدارة",
    // Process page
    processManagement: "إدارة العمليات",
    processManagementDesc: "إدارة وتتبع جميع عملياتك التجارية في مكان واحد.",
    refreshProcesses: "تحديث العمليات",
    changeViewLayout: "تغيير طريقة العرض",
    processTab: "العمليات",
    auditTab: "التدقيق",
    draftTab: "مسودة",
    templateLibraryTab: "مكتبة القوالب",
    total: "الإجمالي",
    visible: "مرئي",
    daily: "يومي",
    weekly: "أسبوعي",
    monthly: "شهري",
    other: "أخرى",
    processes: "عمليات",
    filterProcesses: "تصفية العمليات",
    searchProcess: "بحث عملية",
    searchProcessesByKeyword: "البحث عن العمليات بالكلمة المفتاحية",
    filterByStatus: "تصفية حسب الحالة",
    all: "الكل",
    sortBy: "ترتيب حسب",
    sortProcesses: "ترتيب العمليات",
    applyFilters: "تطبيق الفلاتر",
    resetFilters: "إعادة تعيين الفلاتر",
    exportAsCSV: "تصدير كـ CSV",
    exportAsExcel: "تصدير كـ Excel",
    exportAsPDF: "تصدير كـ PDF",
    exportProcesses: "تصدير العمليات",
    createNewProcess: "إنشاء عملية جديدة",
    formId: "معرف النموذج",
    processTag: "علامة العملية",
    assignees: "المسندون",
    schedule: "الجدول",
    noProcessesAvailable: "لا توجد عمليات متاحة",
    createFirstProcess: "أنشئ أول عملية للبدء",
    viewAndManageAuditTrails: "عرض وإدارة سجلات التدقيق",
    draftProcesses: "عمليات مسودة",
    continueWorkingOnDrafts: "متابعة العمل على مسوداتك",
    browseAndUseTemplates: "تصفح واستخدم قوالب العمليات",
    // Dashboard page
    activityOverview: "نظرة عامة على النشاط",
    viewActivityOverview: "عرض نظرة عامة على النشاط",
    summaryAnalytics: "التحليلات الملخصة",
    viewSummaryAnalytics: "عرض التحليلات الملخصة",
    customReports: "التقارير المخصصة",
    viewCustomReports: "عرض التقارير المخصصة",
    actionPoint: "نقطة العمل",
    ticket: "تذكرة",
    moreInfoAbout: "مزيد من المعلومات حول",
    assigned: "مسند",
    tasksInQueue: "المهام في قائمة الانتظار",
    viewAllTasksInQueue: "عرض جميع المهام في قائمة الانتظار",
    previousDates: "التواريخ السابقة",
    nextDates: "التواريخ التالية",
    viewTaskDetails: "عرض تفاصيل {task}",
    viewAllNotices: "عرض جميع الإشعارات",
    playVideo: "تشغيل الفيديو",
    likeThisNotice: "إعجاب بهذا الإشعار",
    dislikeThisNotice: "عدم الإعجاب بهذا الإشعار",
    viewDiscussions: "عرض المناقشات",
    alertsAndActivity: "التنبيهات والنشاط",
    summaryAnalyticsContentComingSoon: "محتوى التحليلات الملخصة قادم قريباً",
    customReportsContentComingSoon: "محتوى التقارير المخصصة قادم قريباً",
    // Tasks page
    actionPointTab: "نقطة العمل",
    approvalsTab: "الموافقات",
    workflowStatusTab: "حالة سير العمل",
    searchProcesses: "البحث عن العمليات",
    allPeriods: "جميع الفترات",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    filterByCategory: "تصفية حسب الفئة",
    filterByTimePeriod: "تصفية حسب الفترة الزمنية",
    noProcessesMatchCriteria: "لا توجد عمليات تطابق معاييرك.",
    assignedToMe: "مسند إلي",
    createdByMe: "أنشأته أنا",
    closureAssigned: "مسند للإغلاق",
    searchActionPoints: "البحث عن نقاط العمل",
    selectDate: "اختر تاريخ",
    open: "مفتوح",
    onHold: "معلق",
    closed: "مغلق",
    rejected: "مرفوض",
    overdue: "متأخر",
    onTime: "في الوقت",
    dueToday: "مستحق اليوم",
    filterBy: "تصفية حسب",
    filterByActivityStatus: "تصفية حسب حالة النشاط",
    lastUpdatedToday: "آخر تحديث: اليوم",
    loadMore: "تحميل المزيد",
    loadMoreActionPoints: "تحميل المزيد من نقاط العمل",
    exportActionPointsData: "تصدير بيانات نقاط العمل",
    noActionPointsAvailable: "لا توجد نقاط عمل متاحة لهذه الفترة الزمنية. حاول اختيار فترة زمنية مختلفة :)",
    searchApprovals: "البحث عن الموافقات",
    noApprovalsMatchCriteria: "لا توجد موافقات تطابق معاييرك.",
    searchWorkflows: "البحث عن سير العمل",
    noWorkflowsMatchCriteria: "لا يوجد سير عمل يطابق معاييرك.",
    // Noticeboard page
    manageAnnouncementsAndUpdates: "إدارة الإعلانات والتحديثات",
    newPost: "منشور جديد",
    createNoticeboardPost: "إنشاء منشور لوحة الإعلانات",
    createNewAnnouncementOrUpdate: "إنشاء إعلان أو تحديث جديد لفريقك.",
    enterPostTitle: "أدخل عنوان المنشور",
    enterPostDescription: "أدخل وصف المنشور",
    mediaTypeOptional: "نوع الوسائط (اختياري)",
    selectMediaType: "اختر نوع الوسائط",
    mediaUrlOptional: "رابط الوسائط (اختياري)",
    enterMediaUrl: "أدخل رابط الوسائط",
    discussionsEnabled: "المناقشات مفعلة",
    discussionsDisabled: "المناقشات معطلة",
    createPost: "إنشاء منشور",
    searchPosts: "البحث في المنشورات",
    noNoticeboardPostsAvailable: "لا توجد منشورات في لوحة الإعلانات",
    createdBy: "أنشأه",
    unknown: "غير معروف",
    editNoticeboardPost: "تعديل منشور لوحة الإعلانات",
    updateNoticeboardPostDetails: "تحديث تفاصيل منشور لوحة الإعلانات.",
    updatePost: "تحديث المنشور",
    areYouSureDeletePost: "هل أنت متأكد من أنك تريد حذف هذا المنشور؟",
    // ActionPoints page
    manageAndTrackActionItems: "إدارة وتتبع عناصر العمل",
    exportShown: "تصدير المعروض",
    exportAll: "تصدير الكل",
    newActionPoint: "نقطة عمل جديدة",
    priority: "الأولوية",
    allPriority: "جميع الأولويات",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    moreFilters: "المزيد من الفلاتر",
    totalActionPoints: "إجمالي نقاط العمل",
    id: "المعرف",
    assignedTo: "مسند إلى",
    timeLeft: "الوقت المتبقي",
    view: "عرض",
    viewDetails: "عرض التفاصيل",
    actionPointDetails: "تفاصيل نقطة العمل",
    viewAndManageActionPointDetails: "عرض وإدارة تفاصيل نقطة العمل.",
    comments: "التعليقات",
    noDescription: "لا يوجد وصف",
    addComment: "إضافة تعليق",
    startProgress: "بدء التقدم",
    markComplete: "تحديد كمكتمل",
    putOnHold: "وضع في الانتظار",
    enterYourComment: "أدخل تعليقك...",
    noDueDate: "لا يوجد تاريخ استحقاق",
    oneDay: "يوم واحد",
    days: "أيام",
    // Attendance page
    attendanceTracking: "تتبع الحضور",
    trackAndManageEmployeeAttendance: "تتبع وإدارة حضور الموظفين",
    toggleAttendanceOnOff: "تبديل الحضور تشغيل/إيقاف للمؤسسة",
    enforcesGpsBasedCheckInOut: "فرز تسجيل الدخول/الخروج بناءً على GPS (فقط من الجوال)",
    requiresUserToTakeSelfie: "يتطلب من المستخدم التقاط صورة شخصية أثناء تسجيل الدخول",
    requiresSelfieOnCheckOut: "يتطلب صورة شخصية عند تسجيل الخروج",
    startTime: "وقت البدء",
    defineWhenStoreWorkdayStarts: "تحديد متى يبدأ يوم العمل للمتجر",
    endTime: "وقت الانتهاء",
    defineWhenStoreWorkdayEnds: "تحديد متى ينتهي يوم العمل للمتجر",
    setHowManyHoursCountAsCompleteWorkday: "تحديد عدد الساعات التي تعتبر يوماً عمل كاملاً",
    calculateTimeDifferenceOvertime: "حساب فرق الوقت (العمل الإضافي)",
    automaticallyCalculateOverUnderTime: "حساب وقت العمل الإضافي/النقص تلقائياً",
    saveConfiguration: "حفظ التكوين",
    publishAttendanceSettings: "نشر إعدادات الحضور",
    assignAttendancePolicies: "تعيين سياسات الحضور للمتاجر أو المستخدمين أو تحميل التعيينات",
    byStore: "حسب المتجر",
    byUser: "حسب المستخدم",
    searchStores: "البحث في المتاجر...",
    noStoresSelected: "لم يتم تحديد متاجر",
    searchUsers: "البحث في المستخدمين...",
    noUsersSelected: "لم يتم تحديد مستخدمين",
    dragAndDropFileHere: "اسحب وأفلت ملفك هنا، أو انقر للاستعراض",
    chooseFile: "اختر ملف",
    downloadAttendanceReport: "تنزيل تقرير الحضور",
    addStore: "إضافة متجر",
    addUser: "إضافة مستخدم",
    selectStoresToAssignAttendancePolicies: "اختر المتاجر لتعيين سياسات الحضور",
    selectUsersToAssignAttendancePolicies: "اختر المستخدمين لتعيين سياسات الحضور",
    loadingStores: "جاري تحميل المتاجر...",
    noStoresAvailable: "لا توجد متاجر متاحة",
    loadingUsers: "جاري تحميل المستخدمين...",
    noUsersAvailable: "لا يوجد مستخدمين متاحين",
    added: "تمت الإضافة",
    searchByUserNameOrId: "البحث باسم المستخدم أو المعرف...",
    searchAttendanceRecords: "البحث في سجلات الحضور",
    filterByDateRange: "تصفية حسب نطاق التاريخ",
    kpiOverview: "نظرة عامة على مؤشرات الأداء",
    totalRecords: "إجمالي السجلات",
    totalAttendanceEntriesAvailable: "إجمالي إدخالات الحضور المتاحة في هذه الفترة",
    daysCovered: "الأيام المشمولة",
    totalDistinctDaysIncluded: "إجمالي الأيام المميزة المشمولة",
    uniqueEmployeesWithAtLeastOnePunch: "الموظفون الفريدون الذين لديهم تسجيل دخول واحد على الأقل",
    uniqueStoresWithAttendanceActivity: "المتاجر الفريدة مع نشاط الحضور",
    totalScheduledHoursBasedOnWorkingHours: "إجمالي الساعات المجدولة بناءً على ساعات العمل",
    hoursCalculatedFromPunchInOut: "الساعات المحسوبة من تسجيل الدخول/الخروج",
    actualHoursVsExpectedHours: "الساعات الفعلية مقابل الساعات المتوقعة",
    hoursWorkedBeyondExpected: "الساعات التي تم العمل فيها أكثر من المتوقع",
    hoursShortOfExpectedTime: "الساعات أقل من الوقت المتوقع",
    entriesWithoutValidPunchOut: "الإدخالات بدون تسجيل خروج صالح",
    loadingAttendanceRecords: "جاري تحميل سجلات الحضور...",
    present: "حاضر",
    absent: "غائب",
    late: "متأخر",
    checkedIn: "تم تسجيل الدخول",
    onLeave: "في إجازة",
    noData: "لا توجد بيانات",
    name: "الاسم",
    employeeId: "معرف الموظف",
    punchIn: "تسجيل الدخول",
    punchInImage: "صورة تسجيل الدخول",
    punchOut: "تسجيل الخروج",
    punchOutImage: "صورة تسجيل الخروج",
    timeSpent: "الوقت المستغرق",
    // Login page
    checkingSystemStatus: "جاري التحقق من حالة النظام...",
    streamlineBusinessOperations: "تبسيط عمليات عملك مع منصة الإدارة الشاملة الخاصة بنا. تتبع الامتثال، وإدارة الفرق، وتحسين سير العمل كل في مكان واحد.",
    branches: "الفروع",
    compliance: "الامتثال",
    teamMembers: "أعضاء الفريق",
    pleaseEnterDetailsSignIn: "الرجاء إدخال تفاصيلك لتسجيل الدخول",
    enterYourEmail: "أدخل بريدك الإلكتروني",
    enterYourPassword: "أدخل كلمة المرور",
    keepMeSignedIn: "ابقني مسجلاً",
    forgotPassword: "نسيت كلمة المرور؟",
    contactSupport: "اتصل بالدعم",
    itHelpdesk: "مكتب المساعدة التقني",
    demoCredentials: "بيانات تجريبية:",
    invalidEmailOrPassword: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    failedToConnectToServer: "فشل الاتصال بالخادم. يرجى المحاولة مرة أخرى.",
    // Settings page
    generalSettings: "الإعدادات العامة",
    configureSystemPreferences: "تكوين تفضيلات النظام",
    general: "عام",
    security: "الأمان",
    platformName: "اسم المنصة",
    timezone: "المنطقة الزمنية",
    twoFactorAuthentication: "المصادقة الثنائية",
    sessionTimeout: "انتهاء الجلسة",
    fromEmail: "البريد الإلكتروني المرسل",
    emailNotifications: "إشعارات البريد الإلكتروني",
    pushNotifications: "الإشعارات الفورية",
    smsNotifications: "إشعارات الرسائل النصية",
    configureSettings: "تكوين إعدادات {title}",
    cancelChanges: "إلغاء التغييرات",
    saveSettings: "حفظ الإعدادات",
    saveAllSettings: "حفظ جميع الإعدادات",
    // NotFound page
    pageNotFound: "الصفحة غير موجودة",
    sorryPageDoesntExist: "عذراً، الصفحة التي تبحث عنها غير موجودة.",
    pageMayHaveBeenMovedOrDeleted: "قد تكون الصفحة تم نقلها أو حذفها.",
    goHome: "الذهاب إلى الرئيسية",
    // Notifications page
    notificationSettings: "إعدادات الإشعارات",
    manageNotificationPreferences: "إدارة تفضيلات الإشعارات",
    dailyDigest: "الملخص اليومي",
    urgentOnly: "الطوارئ فقط",
    desktopAlerts: "تنبيهات سطح المكتب",
    mobileAlerts: "تنبيهات الجوال",
    urgentMessagesOnly: "الرسائل العاجلة فقط",
    inAppNotifications: "إشعارات التطبيق",
    soundAlerts: "تنبيهات الصوت",
    configureEmailNotificationSettings: "تكوين إعدادات إشعارات البريد الإلكتروني",
    configurePushNotificationSettings: "تكوين إعدادات الإشعارات الفورية",
    configureSmsNotificationSettings: "تكوين إعدادات إشعارات الرسائل النصية",
    configureInAppNotificationSettings: "تكوين إعدادات إشعارات التطبيق",
    saveNotificationSettings: "حفظ إعدادات الإشعارات",
    // Tags page
    organizeAndAutomateActionsWithTags: "تنظيم وأتمتة الإجراءات باستخدام العلامات",
    advDropdownTag: "علامة القائمة المنسدلة المتقدمة",
    createTag: "إنشاء علامة",
    createAdvancedDropdownTag: "إنشاء علامة قائمة منسدلة متقدمة",
    createDropdownTagWithMultipleValues: "إنشاء علامة قائمة منسدلة بقيم متعددة للاستخدام في العمليات والمهام.",
    rootTagName: "اسم العلامة الجذرية",
    dropdownValues: "قيم القائمة المنسدلة",
    addValue: "إضافة قيمة",
    noAdvancedDropdownTagsAvailable: "لا توجد علامات قائمة منسدلة متقدمة",
    values: "القيم",
    createNewProfile: "إنشاء ملف تعريف جديد",
    createAssigneeProfile: "إنشاء ملف تعريف للمكلف",
    createProfileWithAssignedStoresAndUsers: "إنشاء ملف تعريف مع المتاجر والمستخدمين المعينين لمهام العمل.",
    selectStores: "اختيار المتاجر",
    selectUsers: "اختيار المستخدمين",
    saveProfile: "حفظ الملف التعريفي",
    noAssigneeProfilesAvailable: "لا توجد ملفات تعريف للمكلفين",
    areYouSureYouWantToDeleteThisTag: "هل أنت متأكد أنك تريد حذف هذه العلامة؟",
    areYouSureYouWantToDeleteThisProfile: "هل أنت متأكد أنك تريد حذف هذا الملف التعريفي؟",
    // CategoriesAndCourses page
    shortAnswer: "إجابة قصيرة",
    singleAnswer: "إجابة واحدة",
    multipleAnswer: "إجابات متعددة",
    publishQuiz: "نشر الاختبار",
    publishingQuizConfirmation: "نشر هذا الاختبار سيجعله متاحًا للمستخدمين المعينين. هل أنت متأكد أنك تريد النشر؟",
    loadingCategoriesAndCourses: "جاري تحميل الفئات والدورات...",
    noCategoriesOrCoursesFound: "لم يتم العثور على فئات أو دورات",
    createNewCategoryToGetStarted: "أنشئ فئة جديدة للبدء",
    lastUpdatedAt: "آخر تحديث في",
    noCoursesInThisCategory: "لا توجد دورات في هذه الفئة",
    availableQuizzes: "الاختبارات المتاحة",
    loadingQuizzes: "جاري تحميل الاختبارات...",
    noQuizzesFound: "لم يتم العثور على اختبارات",
    createNewQuizToGetStarted: "أنشئ اختبارًا جديدًا للبدء",
    time: "الوقت",
    passing: "النجاح",
    categoryNameIsRequired: "اسم الفئة مطلوب",
    courseNameIsRequired: "اسم الدورة مطلوب",
    pleaseSelectACategory: "يرجى اختيار فئة",
    categoryCreatedSuccessfully: "تم إنشاء الفئة بنجاح",
    failedToCreateCategory: "فشل إنشاء الفئة",
    categoryDeletedSuccessfully: "تم حذف الفئة بنجاح",
    failedToDeleteCategory: "فشل حذف الفئة",
    categoryUpdatedSuccessfully: "تم تحديث الفئة بنجاح",
    failedToUpdateCategory: "فشل تحديث الفئة",
    courseCreatedSuccessfully: "تم إنشاء الدورة بنجاح",
    failedToCreateCourse: "فشل إنشاء الدورة",
    courseDeletedSuccessfully: "تم حذف الدورة بنجاح",
    failedToDeleteCourse: "فشل حذف الدورة",
    courseUpdatedSuccessfully: "تم تحديث الدورة بنجاح",
    failedToUpdateCourse: "فشل تحديث الدورة",
    quizTitleIsRequired: "عنوان الاختبار مطلوب",
    quizCreatedSuccessfully: "تم إنشاء الاختبار بنجاح",
    failedToCreateQuiz: "فشل إنشاء الاختبار",
    quizAssignedSuccessfully: "تم تعيين الاختبار بنجاح",
    failedToAssignQuiz: "فشل تعيين الاختبار",
    quizPublishedSuccessfully: "تم نشر الاختبار بنجاح",
    failedToPublishQuiz: "فشل نشر الاختبار",
    failedToLoadCategories: "فشل تحميل الفئات",
    // Home page
    examplePage: "صفحة مثال",
    exampleButton: "زر مثال",
    // Draft page
    ticketDashboard: "لوحة التذاكر",
    trackAndManageAllYourTaskTickets: "تتبع وإدارة جميع تذاكر المهام الخاصة بك في مكان واحد.",
    newTicket: "تذكرة جديدة",
    searchTickets: "البحث عن التذاكر...",
    searchTicketsByKeyword: "البحث عن التذاكر بالكلمة المفتاحية",
    searchHelpAndTips: "مساعدة ونصائح البحث",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    applyDateFilter: "تطبيق فلتر التاريخ",
    loadMoreTickets: "تحميل المزيد من التذاكر",
    exportTicketsData: "تصدير بيانات التذاكر",
    noTicketsAvailableForThisDateRange: "لا توجد تذاكر متاحة لهذا النطاق الزمني. حاول اختيار نطاق زمني مختلف :)",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
